// Liko - FCM — Español
(function () {
    var I = window.Liko && window.Liko.__Sys_i18n__;
    if (!I || !I.register) { console.error('[Liko FCM ES] i18n no está disponible'); return; }
    var V = {
        initHint: '🐈‍⬛ FCM v{0} inicializado. Haz clic en el icono «SVG» para gestionar amistades y salas; en el primer uso conviene una configuración sencilla en la página de Ajustes.\n⚠ Nota: las amistades recién añadidas pueden aparecer como «unilaterales» — prueba a eliminarlas y añadirlas de nuevo. Este problema ya se ha reportado a la comunidad.',
        panelTitle: '🎛 FCM ─ Gestor de amistades y salas', tabFriends: 'Relaciones', tabRoom: 'Gestión de sala', tabSettings: 'Ajustes', tabPeople: 'Personas', tabHelp: '🔖 Ayuda', minimize: '—', close: '×', miniLabel: 'Gestor de amistades y salas',
        search: 'Buscar nombre o ID...', roomSearch: 'Buscar / Introducir ID para añadir...', sortBy: 'Ordenar', sortFav: 'Seguidos', sortRel: 'Relación', sortId: 'ID', sortName: 'Nombre', sortAdded: 'Añadido', sortSeen: 'Visto por última vez', showOnly: 'Mostrar', togNick: 'Apodo', togName: 'Nombre',
        fOnline: 'En línea', fOffline: 'Sin conexión', fOwner: 'Dueña', fLover: 'Amante', fSub: 'Sumisa', fFriend: 'Amiga', colName: 'Nombre', colId: 'ID', colRel: 'Rel.', colZone: 'Zona', colRoom: 'Sala', colPerm: 'Perm.', colOps: 'Acciones', colManage: 'Gestionar', colMgmt: 'Administración', colMgmtNoPerm: 'Administración (sin permiso)', colSeen: 'Última vez',
        relOwner: 'Dueña', relLover: 'Amante', relSub: 'Sumisa', relFriend: 'Amiga', relContact: 'Unilateral', relWhitelist: 'Lista blanca', relBlacklist: 'Lista negra', relGhost: 'Fantasma', zoneF: '♀', zoneM: '♂', zoneX: '♀♂', zoneUnk: '—', online: 'En línea', offline: 'Sin conexión',
        btnView: 'Ver', btnBeep: 'BEEP', btnWhisper: 'Mensaje', btnAddFriend: '+Amiga', btnRmFriend: '−Amiga', btnAddAdmin: '＋Admin', btnRmAdmin: '−Admin', btnAddWhite: '＋Blanca', btnRmWhite: '−Blanca', btnAddBan: '＋Veto', btnRmBan: '−Veto', btnKick: 'Expulsar', btnAddBlack: '＋Negra', btnRmBlack: '−Negra', btnAdd: 'Añadir', btnAddTitle: 'Añadir ID a la lista',
        roomTab_members: 'Miembros', roomTab_admin: 'Administradoras', roomTab_white: 'Lista blanca', roomTab_ban: 'Lista negra', notInRoom: 'No estás en ninguna sala', noAdminWarn: '⚠ Sin permisos de administración — la columna solo permite consultar',
        setAvatars: 'Mostrar avatares', setAvatarsNote: 'Muestra retratos (se guardan al encontrarse y se almacenan en FCM-Snapshot DB)', setProfiles: 'Activar guardado automático de perfiles', setProfilesNote: 'Compatible con bce-past-profiles de WCE', dbOk: 'Conectada', dbNo: 'Sin conexión', langLabel: 'Idioma', langNote: 'Auto: sigue TranslationLanguage de BC (CN/TW→chino; el resto→inglés)',
        whisperIndicatorLabel: 'Color del resplandor al susurrar o usar BEEP', whisperIndicatorNote: 'Muestra un resplandor morado en el cuadro de chat al escribir /w, /whisper o /beep, o cuando está activo el modo susurro', ghostHideLabel: 'Ocultar lista fantasma', ghostHideNote: 'Oculta en la sala a los personajes de tu lista fantasma (solo afecta a tu vista)',
        btnReloadAvatars: 'Caché de avatares', reloadAvatarsNote: 'Borra la caché o carga los avatares de tus amigas', btnLoadFriendAvatars: 'Cargar avatares de amigas', loadFriendAvatarsNote: 'Recorre todas tus amigas, espera a que BC almacene sus apariencias y crea capturas (puede tardar decenas de segundos)', btnClearAvatarCache: 'Borrar caché de avatares', clearAvatarCacheNote: 'Elimina todas las capturas guardadas; se crearán otras al volver a encontrarlas', loadFriendAvatarsDone: 'Avatares de amigas cargados', loadingFriendAvatars: 'Cargando avatares... quedan {0}',
        noProfile: 'No hay datos del perfil\n(Debéis haber coincidido en una sala)', confirmDel: '¿Dejar de ser amiga de «{0}»?', confirmKick: '¿Expulsar a «{0}»?', confirmRoom: '🚪 ¿Ir a la sala «{0}»?', confirmAddBan: '¿Añadir a «{0}» a la lista negra?\nYa no podrá interactuar contigo.', confirmAddGhost: '¿Añadir a «{0}» a la lista fantasma?\nDejarás de recibir sus mensajes.',
        tabRoomSearch: 'Buscar salas', roomSearch2: 'Buscar salas...', roomSearchBtn: 'Buscar', roomSearching: 'Buscando...', roomSearchEmpty: 'No se encontraron salas', roomFavLabel: '★ Favoritas', roomJoin: 'Entrar', roomMixed: 'Mixta', roomFemale: 'Femenina', roomMale: 'Masculina', totalRooms: 'Salas: {0}', roomPrivateLabel: 'Privada', permAdmin: 'Admin', permPass: 'Acceso', permBan: 'Veto', permVisit: 'Visita', youLabel: '(Tú)', copyId: 'Haz clic para copiar el ID', copyDone: '¡Copiado!', total: 'Total: {0}',
        beepTitle: 'BEEP → {0}', beepPlaceholder: 'Escribe un mensaje (puede quedar vacío)\nCtrl+Enter para enviar', beepSend: 'Enviar BEEP', beepCancel: 'Cancelar', beepSummon: 'Invocar', beepSummonTitle: 'Debes tener autoridad para invocar a la otra jugadora.\nDe lo contrario, solo recibirá «summon».', beepSummonNoRoom: 'Debes estar en una sala para invocar', noData: '(Vacío)', noFriends: 'No hay resultados', fWhitelist: 'Lista blanca', fBlacklist: 'Lista negra', fGhost: 'Fantasma', roomPrivate: 'Privada', roomPublic: '',
        saveModeLabel: 'Modo de guardado', saveModeOff: 'Desactivado', saveModeName: 'Solo nombre', saveModeAvatar: 'Nombre + avatar', saveModeFull: 'Perfil completo (WCE)', saveModeDesc_off: 'No guarda datos. Si usas los perfiles de WCE, elige esta opción para evitar duplicados (WCE ya los guarda).', saveModeDesc_name: 'Guarda solo el número de miembro, nombre de BC y apodo. Ocupa lo mínimo y permite mostrar los nombres de amigas desconectadas.', saveModeDesc_avatar: 'También guarda una captura del avatar (se obtiene automáticamente al encontrarse y se almacena aparte en FCM-Snapshot DB).', saveModeDesc_full: 'Guardado completo: nombre, apodo, apariencia, BIO, título, etc. Totalmente compatible con bce-past-profiles de WCE. Los avatares se almacenan aparte en FCM-Snapshot.', wceDetected: '✅ Perfiles de WCE detectados — se ha elegido el modo completo (BD compartida, sin conflictos)', wceNotDetected: 'No se detectó WCE. Usa «Solo nombre» para ahorrar espacio o «Nombre + avatar» si quieres retratos.',
        exportProfiles: 'Exportar perfiles', exportNote: 'Exportar como JSON (formato compatible con WCE)', importProfiles: 'Importar perfiles', importNote: 'Importar desde JSON (en caso de conflicto prevalece la fecha más reciente)', exportDone: '✓ Se exportaron {0} perfiles', profilesTitle: 'Perfiles guardados', profilesHint: 'Haz clic para abrir la ficha del personaje', profilesEmpty: 'No hay perfiles coincidentes', profilesTotal: 'Mostrando {0} de {1}', searchProfiles: 'Buscar nombre o ID...',
        peopleSearchPlaceholder: 'Nombre o ID — pulsa Enter para buscar...', peopleSearchHint: 'Se muestran los últimos 100 encuentros · escribe y pulsa Enter o Buscar', peopleNoResults: 'No se encontraron personas', peopleUnknownId: '¿Querías decir #{0}? No hay ningún registro con ese ID.', peopleSimilarIds: 'ID parecidos que contienen este número:', peopleUnknownName: 'Nombre desconocido', peopleOneSidedWarn: '⚠ Nota: esta acción solo añade la relación de tu lado. Si hace falta, avisa tú misma a la otra persona.', peopleTotal: 'Mostrando {0} de {1}',
        colShare: 'Compartir', btnShare: 'Compartir', shareLocalMsg: '📜 Perfil compartido: {0} ({1})', shareRecvMsg: '📜 {0} compartió un perfil: {1}; guardado: {2}', shareOpen: '▶ Abrir', whisperAvatarLabel: 'Mostrar el avatar del destinatario al susurrar', whisperAvatarNote: 'Muestra su avatar junto al cuadro de chat en modo susurro/BEEP', oocProtectLabel: 'Protección OOC (bloquear Ctrl+Enter al susurrar)', oocProtectNote: 'En modo susurro/BEEP, bloquea Ctrl+Enter para evitar enviar contenido OOC al chat normal',
        btnVisibilityLabel: 'Visibilidad del botón', btnVisibilityNote: 'Elige en qué pantallas aparece el botón de FCM (al menos una debe quedar activa)', btnShowChatRoom: 'Botón en la sala', btnShowMainHall: 'Botón en el vestíbulo', btnShowProfile: 'Botón en el perfil', profileRelLabel: 'Búsqueda rápida de relaciones', profileRelNote: 'En un perfil, convierte los ID de personas relacionadas (dueña/amantes) en botones; al pulsarlos abre la búsqueda de personas de FCM con ese ID (requiere guardar perfiles)', profileRelTitle: '🔍 Consulta rápida de relaciones', noBeepNotFriend: 'No es tu amiga — no puedes enviarle un BEEP', colorNone: 'Sin color',
        addFriendTitle: '¿Añadir a «{0}» como amiga?', addFriendNotifyHint: '(Puedes avisarle; requiere FCM)', btnAgree: 'Aceptar', btnAgreeNotify: 'Aceptar y avisar', btnViewProfile: 'Ver', friendReqNeedRoom: 'Debéis estar en la misma sala para avisarle', friendReqIncoming: '{0} te ha enviado una solicitud de amistad. ¿La aceptas?', friendReqSent: '📩 Solicitud de amistad enviada a «{0}»', friendReqAdded: '✓ «{0}» añadida como amiga',
        roomTypeMap: 'Mapa', roomTypeMix: 'Híbrida', roomLockedCanJoin: 'Cerrada — puedes entrar', roomLockedNoAccess: 'Cerrada — sin acceso', roomHereBadge: '🏠 Tú', roomReenter: 'Volver a entrar', roomReenterConfirm: 'Ya estás en «{0}».\n¿Quieres volver a entrar?', btnCancel: 'Cancelar', btnConfirm: 'Confirmar', roomGo: '🚪 Ir', beepSummonConfirm: 'Asegúrate de tener permiso para invocarla; de lo contrario solo recibirá el texto «summon».\n\n¿Invocar a «{0}»?', btnRemove: 'Quitar', btnAddConfirm: 'Añadir', btnRefresh: 'Actualizar', btnAddGhost: '＋Fantasma', btnRmGhost: '−Fantasma', btnClear: 'Borrar', btnClearing: 'Borrando...', btnSearch: 'Buscar',
        confirmRmWhite: '¿Quitar a «{0}» de la lista blanca?', confirmAddWhite: '¿Añadir a «{0}» a la lista blanca?', confirmRmBlack: '¿Quitar a «{0}» de la lista negra?', confirmRmGhost: '¿Quitar a «{0}» de la lista fantasma?', avReloadTitle: 'Haz clic para recargar el avatar', togNickToBCName: 'Cambiar al nombre de BC', togNickToNick: 'Cambiar al apodo', btnSnapshotTitle: 'Capturar la lista actual (forzar reconstrucción)', roomPrivPrefix: '[Privada] ', roomFull: '⚠ Llena', roomGoPrompt: '¿Ir a la sala?', roomPrivShort: '(Priv.)', roomPrivateHidden: '(Privada)', peopleDbNotConnected: 'BD sin conexión — elige un modo de guardado en Ajustes', shareNeedRoom: 'Debes estar en una sala para compartir', pageInfo: 'Página {0} / {1}', sortFavFirst: 'Favoritas primero', sortFriendFirst: 'Amigas primero', sortNameOnly: 'Nombre',
        setSecUI: '⚙ Interfaz', setSecChat: '⚙ Sala de chat', avCacheCleared: '✓ Caché borrada', noFriendsToLoad: 'No hay avatares de amigas por cargar', avWaitLeft: 'Esperando a BC... quedan {0} s', avWait: 'Esperando a BC... {0} s', avSnapshotting: 'Creando capturas...', wceTagDetected: 'WCE detectado', colorEditLabel: 'Color', cmdProfilesDesc: '<filtro> - Abrir búsqueda de personas (por nombre o ID)', roomShareBtn: 'Compartir', roomJoinRoomBtn: 'Entrar en la sala', roomShareNeedRoom: 'Debes estar en una sala para compartir', roomShareIntro: '{0} compartió una sala', roomShareLocalDone: '📤 Sala «{0}» compartida en el chat', themeColorLabel: 'Colores del tema', themeColorNote: 'Personaliza el fondo, el texto y el color de énfasis (bordes, pestañas y resplandor)', themePanelColor: 'Panel', themeFontColor: 'Texto', themeAccentColor: 'Énfasis', themeReset: 'Restablecer', whisperNoSignal: 'Sin señal', importDone: '✓ Perfiles importados: {0}; notas: {1}', reloadStatusLoading: 'Cargando avatares... quedan {0}; espera', reloadStatusDone: 'Avatares cargados'
    };
    var T = {}; Object.keys(V).forEach(function (k) { T[k] = { ES: V[k] }; });
    I.register('FCM', T);
})();
