// Liko - FCM i18n 字庫
// 此檔案由 FCM 插件動態載入，不需手動安裝
// 載入後自動呼叫 register('FCM', {...})，將字串注入共用引擎 BC_i18n（window.Liko.__Sys_i18n__）
// 佔位符以 {0} {1} {2} 表示位置參數，由 FCM 的 T(key, ...args) 依序代入
// 語言：TW 繁中 / CN 簡中 / EN 英 / JP 日 / KR 韓 / DE 德 / FR 法 / RU 俄 / UA 烏

(function () {
    if (!window.Liko?.__Sys_i18n__?.register) {
        console.error('[Liko FCM strings] i18n 引擎尚未載入');
        return;
    }

    const FCM_STRINGS = {
        // ── 面板 / 分頁 ─────────────────────────────────────────────
        'panelTitle': { TW: '🎛 FCM ─ 好友與房間管理', CN: '🎛 FCM ─ 好友与房间管理', EN: '🎛 FCM ─ Friends and ChatRoom Manager', JP: '🎛 FCM ─ フレンド＆ルーム管理', KR: '🎛 FCM ─ 친구 및 방 관리', DE: '🎛 FCM ─ Freunde- und Raum-Manager', FR: '🎛 FCM ─ Gestionnaire d\'amis et de salons', RU: '🎛 FCM ─ Менеджер друзей и комнат', UA: '🎛 FCM ─ Менеджер друзів і кімнат' },
        'tabFriends': { TW: '個人關係', CN: '个人关系', EN: 'Relations', JP: '関係', KR: '관계', DE: 'Beziehungen', FR: 'Relations', RU: 'Связи', UA: 'Зв\'язки' },
        'tabRoom': { TW: '房間管理', CN: '房间管理', EN: 'Room Mgmt', JP: 'ルーム管理', KR: '방 관리', DE: 'Raum-Verw.', FR: 'Gest. salon', RU: 'Комната', UA: 'Кімната' },
        'tabSettings': { TW: '設定', CN: '设置', EN: 'Settings', JP: '設定', KR: '설정', DE: 'Einstellungen', FR: 'Réglages', RU: 'Настройки', UA: 'Налаштування' },
        'tabPeople': { TW: '人員查詢', CN: '人员查询', EN: 'People', JP: '人物検索', KR: '인물 검색', DE: 'Personen', FR: 'Personnes', RU: 'Люди', UA: 'Люди' },
        'tabHelp': { TW: '🔖 說明', CN: '🔖 说明', EN: '🔖 Help', JP: '🔖 ヘルプ', KR: '🔖 도움말', DE: '🔖 Hilfe', FR: '🔖 Aide', RU: '🔖 Справка', UA: '🔖 Довідка' },
        'minimize': { TW: '—', CN: '—', EN: '—', JP: '—', KR: '—', DE: '—', FR: '—', RU: '—', UA: '—' },
        'close': { TW: '×', CN: '×', EN: '×', JP: '×', KR: '×', DE: '×', FR: '×', RU: '×', UA: '×' },
        'miniLabel': { TW: '好友與房間管理', CN: '好友与房间管理', EN: 'Friends and ChatRoom Manager', JP: 'フレンド＆ルーム管理', KR: '친구 및 방 관리', DE: 'Freunde- und Raum-Manager', FR: 'Gestionnaire d\'amis et de salons', RU: 'Менеджер друзей и комнат', UA: 'Менеджер друзів і кімнат' },

        // ── 工具列 / 排序 / 篩選 ────────────────────────────────────
        'search': { TW: '搜尋名稱或ID...', CN: '搜索名称或ID...', EN: 'Search name or ID...', JP: '名前かIDを検索...', KR: '이름 또는 ID 검색...', DE: 'Name oder ID suchen...', FR: 'Chercher nom ou ID...', RU: 'Поиск по имени или ID...', UA: 'Пошук за іменем або ID...' },
        'roomSearch': { TW: '搜尋 / 輸入ID添加...', CN: '搜索 / 输入ID添加...', EN: 'Search / Enter ID to add...', JP: '検索 / IDを入力して追加...', KR: '검색 / ID 입력하여 추가...', DE: 'Suchen / ID eingeben...', FR: 'Chercher / saisir ID...', RU: 'Поиск / ввести ID...', UA: 'Пошук / введіть ID...' },
        'sortBy': { TW: '排序', CN: '排序', EN: 'Sort', JP: '並び替え', KR: '정렬', DE: 'Sortieren', FR: 'Trier', RU: 'Сортировка', UA: 'Сортування' },
        'sortRel': { TW: '關係', CN: '关系', EN: 'Relation', JP: '関係', KR: '관계', DE: 'Beziehung', FR: 'Relation', RU: 'Связь', UA: 'Зв\'язок' },
        'sortId': { TW: 'ID', CN: 'ID', EN: 'ID', JP: 'ID', KR: 'ID', DE: 'ID', FR: 'ID', RU: 'ID', UA: 'ID' },
        'sortName': { TW: '名稱', CN: '名称', EN: 'Name', JP: '名前', KR: '이름', DE: 'Name', FR: 'Nom', RU: 'Имя', UA: 'Ім\'я' },
        'sortAdded': { TW: '添加時間', CN: '添加时间', EN: 'Added', JP: '追加日', KR: '추가일', DE: 'Hinzugefügt', FR: 'Ajouté', RU: 'Добавлен', UA: 'Додано' },
        'sortSeen': { TW: '最後見面', CN: '最后见面', EN: 'Last Seen', JP: '最終遭遇', KR: '마지막 만남', DE: 'Zuletzt gesehen', FR: 'Vu récemment', RU: 'Был замечен', UA: 'Востаннє бачили' },
        'showOnly': { TW: '顯示', CN: '显示', EN: 'Show', JP: '表示', KR: '표시', DE: 'Zeigen', FR: 'Afficher', RU: 'Показать', UA: 'Показати' },
        'togNick': { TW: '暱稱', CN: '昵称', EN: 'Nick', JP: 'ニックネーム', KR: '닉네임', DE: 'Spitzn.', FR: 'Surnom', RU: 'Ник', UA: 'Нік' },
        'togName': { TW: '名稱', CN: '名称', EN: 'Name', JP: '名前', KR: '이름', DE: 'Name', FR: 'Nom', RU: 'Имя', UA: 'Ім\'я' },
        'fOnline': { TW: '在線', CN: '在线', EN: 'Online', JP: 'オンライン', KR: '온라인', DE: 'Online', FR: 'En ligne', RU: 'В сети', UA: 'У мережі' },
        'fOffline': { TW: '不在線', CN: '不在线', EN: 'Offline', JP: 'オフライン', KR: '오프라인', DE: 'Offline', FR: 'Hors ligne', RU: 'Не в сети', UA: 'Не в мережі' },
        'fOwner': { TW: '主人', CN: '主人', EN: 'Owner', JP: 'マスター', KR: '주인', DE: 'Besitzer', FR: 'Maître', RU: 'Владелец', UA: 'Власник' },
        'fLover': { TW: '戀人', CN: '恋人', EN: 'Lover', JP: '恋人', KR: '연인', DE: 'Geliebte', FR: 'Amant', RU: 'Возлюбленный', UA: 'Коханий' },
        'fSub': { TW: '奴隸', CN: '奴隶', EN: 'Sub', JP: '奴隷', KR: '노예', DE: 'Sub', FR: 'Soumis', RU: 'Раб', UA: 'Раб' },
        'fFriend': { TW: '好友', CN: '好友', EN: 'Friend', JP: 'フレンド', KR: '친구', DE: 'Freund', FR: 'Ami', RU: 'Друг', UA: 'Друг' },

        // ── 表格欄位 ─────────────────────────────────────────────────
        'colName': { TW: '名稱', CN: '名称', EN: 'Name', JP: '名前', KR: '이름', DE: 'Name', FR: 'Nom', RU: 'Имя', UA: 'Ім\'я' },
        'colId': { TW: 'ID', CN: 'ID', EN: 'ID', JP: 'ID', KR: 'ID', DE: 'ID', FR: 'ID', RU: 'ID', UA: 'ID' },
        'colRel': { TW: '關係', CN: '关系', EN: 'Rel.', JP: '関係', KR: '관계', DE: 'Bez.', FR: 'Rel.', RU: 'Связь', UA: 'Зв\'язок' },
        'colZone': { TW: '分區', CN: '分区', EN: 'Zone', JP: 'ゾーン', KR: '구역', DE: 'Zone', FR: 'Zone', RU: 'Зона', UA: 'Зона' },
        'colRoom': { TW: '房間', CN: '房间', EN: 'Room', JP: 'ルーム', KR: '방', DE: 'Raum', FR: 'Salon', RU: 'Комната', UA: 'Кімната' },
        'colPerm': { TW: '權限', CN: '权限', EN: 'Perm.', JP: '権限', KR: '권한', DE: 'Rechte', FR: 'Droits', RU: 'Права', UA: 'Права' },
        'colOps': { TW: '動作', CN: '动作', EN: 'Actions', JP: '操作', KR: '동작', DE: 'Aktionen', FR: 'Actions', RU: 'Действия', UA: 'Дії' },
        'colMgmt': { TW: '房管', CN: '房管', EN: 'Room Admin', JP: 'ルーム管理', KR: '방 관리', DE: 'Raum-Admin', FR: 'Admin salon', RU: 'Админ комнаты', UA: 'Адмін кімнати' },
        'colMgmtNoPerm': { TW: '房管（無權）', CN: '房管（无权）', EN: 'Room Admin (no perm)', JP: 'ルーム管理（権限なし）', KR: '방 관리 (권한 없음)', DE: 'Raum-Admin (keine Rechte)', FR: 'Admin salon (sans droit)', RU: 'Админ комнаты (нет прав)', UA: 'Адмін кімнати (немає прав)' },
        'colSeen': { TW: '最後見面', CN: '最后见面', EN: 'Last Seen', JP: '最終遭遇', KR: '마지막 만남', DE: 'Zuletzt gesehen', FR: 'Vu récemment', RU: 'Был замечен', UA: 'Востаннє бачили' },

        // ── 關係標籤 ─────────────────────────────────────────────────
        'relOwner': { TW: '主人', CN: '主人', EN: 'Owner', JP: 'マスター', KR: '주인', DE: 'Besitzer', FR: 'Maître', RU: 'Владелец', UA: 'Власник' },
        'relLover': { TW: '戀人', CN: '恋人', EN: 'Lover', JP: '恋人', KR: '연인', DE: 'Geliebte', FR: 'Amant', RU: 'Возлюбленный', UA: 'Коханий' },
        'relSub': { TW: '奴隸', CN: '奴隶', EN: 'Sub', JP: '奴隷', KR: '노예', DE: 'Sub', FR: 'Soumis', RU: 'Раб', UA: 'Раб' },
        'relFriend': { TW: '好友', CN: '好友', EN: 'Friend', JP: 'フレンド', KR: '친구', DE: 'Freund', FR: 'Ami', RU: 'Друг', UA: 'Друг' },
        'relContact': { TW: '單向好友', CN: '单向好友', EN: 'One-way', JP: '片方向', KR: '일방향', DE: 'Einseitig', FR: 'Unilatéral', RU: 'Односторонний', UA: 'Односторонній' },
        'relWhitelist': { TW: '白名單', CN: '白名单', EN: 'WL', JP: 'WL', KR: 'WL', DE: 'WL', FR: 'LB', RU: 'БС', UA: 'БС' },
        'relBlacklist': { TW: '黑名單', CN: '黑名单', EN: 'BL', JP: 'BL', KR: 'BL', DE: 'BL', FR: 'LN', RU: 'ЧС', UA: 'ЧС' },
        'relGhost': { TW: '幽靈', CN: '幽灵', EN: 'Ghost', JP: 'ゴースト', KR: '고스트', DE: 'Geist', FR: 'Fantôme', RU: 'Призрак', UA: 'Привид' },

        // ── 分區 / 在線 ──────────────────────────────────────────────
        'zoneF': { TW: '♀', CN: '♀', EN: '♀', JP: '♀', KR: '♀', DE: '♀', FR: '♀', RU: '♀', UA: '♀' },
        'zoneM': { TW: '♂', CN: '♂', EN: '♂', JP: '♂', KR: '♂', DE: '♂', FR: '♂', RU: '♂', UA: '♂' },
        'zoneX': { TW: '♀♂', CN: '♀♂', EN: '♀♂', JP: '♀♂', KR: '♀♂', DE: '♀♂', FR: '♀♂', RU: '♀♂', UA: '♀♂' },
        'zoneUnk': { TW: '—', CN: '—', EN: '—', JP: '—', KR: '—', DE: '—', FR: '—', RU: '—', UA: '—' },
        'online': { TW: '在線', CN: '在线', EN: 'Online', JP: 'オンライン', KR: '온라인', DE: 'Online', FR: 'En ligne', RU: 'В сети', UA: 'У мережі' },
        'offline': { TW: '不在線', CN: '不在线', EN: 'Offline', JP: 'オフライン', KR: '오프라인', DE: 'Offline', FR: 'Hors ligne', RU: 'Не в сети', UA: 'Не в мережі' },

        // ── 動作按鈕 ─────────────────────────────────────────────────
        'btnView': { TW: '查看', CN: '查看', EN: 'View', JP: '表示', KR: '보기', DE: 'Ansehen', FR: 'Voir', RU: 'Профиль', UA: 'Профіль' },
        'btnBeep': { TW: '私信', CN: '私信', EN: 'BEEP', JP: 'BEEP', KR: 'BEEP', DE: 'BEEP', FR: 'BEEP', RU: 'BEEP', UA: 'BEEP' },
        'btnWhisper': { TW: '悄悄話', CN: '悄悄话', EN: 'Msg', JP: 'ささやき', KR: '귓속말', DE: 'Flüstern', FR: 'Chuchoter', RU: 'Шёпот', UA: 'Шепіт' },
        'btnAddFriend': { TW: '＋好友', CN: '＋好友', EN: '+Frnd', JP: '＋フレンド', KR: '＋친구', DE: '+Freund', FR: '+Ami', RU: '+Друг', UA: '+Друг' },
        'btnRmFriend': { TW: '－好友', CN: '－好友', EN: '-Frnd', JP: '－フレンド', KR: '－친구', DE: '-Freund', FR: '-Ami', RU: '-Друг', UA: '-Друг' },
        'btnAddAdmin': { TW: '＋管理', CN: '＋管理', EN: '＋Admin', JP: '＋管理', KR: '＋관리', DE: '＋Admin', FR: '＋Admin', RU: '＋Админ', UA: '＋Адмін' },
        'btnRmAdmin': { TW: '－管理', CN: '－管理', EN: '－Admin', JP: '－管理', KR: '－관리', DE: '－Admin', FR: '－Admin', RU: '－Админ', UA: '－Адмін' },
        'btnAddWhite': { TW: '＋白單', CN: '＋白单', EN: '＋White', JP: '＋白', KR: '＋화이트', DE: '＋Whitel.', FR: '＋Blanche', RU: '＋БелСп', UA: '＋БілСп' },
        'btnRmWhite': { TW: '－白單', CN: '－白单', EN: '－White', JP: '－白', KR: '－화이트', DE: '－Whitel.', FR: '－Blanche', RU: '－БелСп', UA: '－БілСп' },
        'btnAddBan': { TW: '＋黑單', CN: '＋黑单', EN: '＋BAN', JP: '＋BAN', KR: '＋BAN', DE: '＋BANN', FR: '＋BAN', RU: '＋БАН', UA: '＋БАН' },
        'btnRmBan': { TW: '－黑單', CN: '－黑单', EN: '－BAN', JP: '－BAN', KR: '－BAN', DE: '－BANN', FR: '－BAN', RU: '－БАН', UA: '－БАН' },
        'btnKick': { TW: '逐出', CN: '逐出', EN: 'Kick', JP: 'キック', KR: '추방', DE: 'Kicken', FR: 'Expulser', RU: 'Выгнать', UA: 'Вигнати' },
        'btnAddBlack': { TW: '＋黑單', CN: '＋黑单', EN: '＋Black', JP: '＋黒', KR: '＋블랙', DE: '＋Blackl.', FR: '＋Noire', RU: '＋ЧёрСп', UA: '＋ЧорСп' },
        'btnRmBlack': { TW: '－黑單', CN: '－黑单', EN: '－Black', JP: '－黒', KR: '－블랙', DE: '－Blackl.', FR: '－Noire', RU: '－ЧёрСп', UA: '－ЧорСп' },
        'btnAdd': { TW: '添加', CN: '添加', EN: 'Add', JP: '追加', KR: '추가', DE: 'Hinzuf.', FR: 'Ajouter', RU: 'Добавить', UA: 'Додати' },
        'btnAddTitle': { TW: '添加ID到名單', CN: '添加ID到名单', EN: 'Add ID to list', JP: 'IDをリストに追加', KR: 'ID를 목록에 추가', DE: 'ID zur Liste hinzufügen', FR: 'Ajouter l\'ID à la liste', RU: 'Добавить ID в список', UA: 'Додати ID до списку' },

        // ── 房管子分頁 ───────────────────────────────────────────────
        'roomTab_members': { TW: '房內人員', CN: '房内人员', EN: 'Members', JP: 'メンバー', KR: '멤버', DE: 'Mitglieder', FR: 'Membres', RU: 'Участники', UA: 'Учасники' },
        'roomTab_admin': { TW: '管理者', CN: '管理者', EN: 'Admins', JP: '管理者', KR: '관리자', DE: 'Admins', FR: 'Admins', RU: 'Админы', UA: 'Адміни' },
        'roomTab_white': { TW: '白名單', CN: '白名单', EN: 'Whitelist', JP: 'ホワイトリスト', KR: '화이트리스트', DE: 'Whitelist', FR: 'Liste blanche', RU: 'Белый список', UA: 'Білий список' },
        'roomTab_ban': { TW: '黑名單', CN: '黑名单', EN: 'Blacklist', JP: 'ブラックリスト', KR: '블랙리스트', DE: 'Blacklist', FR: 'Liste noire', RU: 'Чёрный список', UA: 'Чорний список' },
        'notInRoom': { TW: '目前不在任何房間中', CN: '目前不在任何房间中', EN: 'Not currently in a room', JP: '現在どのルームにもいません', KR: '현재 방에 있지 않습니다', DE: 'Derzeit in keinem Raum', FR: 'Actuellement dans aucun salon', RU: 'Сейчас не в комнате', UA: 'Зараз не в кімнаті' },
        'noAdminWarn': { TW: '⚠ 無管理員權限，房管欄僅供查看', CN: '⚠ 无管理员权限，房管栏仅供查看', EN: '⚠ No admin rights — Room Admin column is view-only', JP: '⚠ 管理者権限がありません。ルーム管理列は閲覧のみ', KR: '⚠ 관리자 권한 없음 — 방 관리 열은 보기 전용', DE: '⚠ Keine Admin-Rechte — Raum-Admin-Spalte nur lesbar', FR: '⚠ Pas de droits admin — colonne Admin salon en lecture seule', RU: '⚠ Нет прав админа — столбец «Админ комнаты» только для просмотра', UA: '⚠ Немає прав адміна — стовпець «Адмін кімнати» лише для перегляду' },

        // ── 設定：頭像 / 資料 ────────────────────────────────────────
        'setAvatars': { TW: '顯示頭像', CN: '显示头像', EN: 'Show Avatars', JP: 'アバターを表示', KR: '아바타 표시', DE: 'Avatare anzeigen', FR: 'Afficher les avatars', RU: 'Показывать аватары', UA: 'Показувати аватари' },
        'setAvatarsNote': { TW: '在列表中顯示角色頭像（見過後才有，或由角色資料重建）', CN: '在列表中显示角色头像（见过后才有，或由角色资料重建）', EN: 'Show portraits (saved on encounter, stored in FCM-Snapshot DB)', JP: 'リストにアバターを表示（遭遇時に保存、FCM-Snapshot DB に格納）', KR: '목록에 아바타 표시 (만났을 때 저장, FCM-Snapshot DB에 보관)', DE: 'Porträts anzeigen (bei Begegnung gespeichert, in FCM-Snapshot-DB)', FR: 'Afficher les portraits (enregistrés lors d\'une rencontre, dans la BD FCM-Snapshot)', RU: 'Показывать портреты (сохраняются при встрече, в БД FCM-Snapshot)', UA: 'Показувати портрети (зберігаються при зустрічі, у БД FCM-Snapshot)' },
        'setProfiles': { TW: '啟用自動儲存個人資料', CN: '启用自动保存个人资料', EN: 'Enable Profile Auto-Save', JP: 'プロフィール自動保存を有効化', KR: '프로필 자동 저장 활성화', DE: 'Profil-Autospeicherung aktivieren', FR: 'Activer l\'enreg. auto des profils', RU: 'Автосохранение профилей', UA: 'Автозбереження профілів' },
        'setProfilesNote': { TW: '與 WCE bce-past-profiles 相容，同房間時自動儲存', CN: '与 WCE bce-past-profiles 兼容，同房间时自动保存', EN: 'WCE bce-past-profiles compatible', JP: 'WCE bce-past-profiles と互換', KR: 'WCE bce-past-profiles 호환', DE: 'Kompatibel mit WCE bce-past-profiles', FR: 'Compatible avec WCE bce-past-profiles', RU: 'Совместимо с WCE bce-past-profiles', UA: 'Сумісно з WCE bce-past-profiles' },
        'dbOk': { TW: '已連線', CN: '已连接', EN: 'Connected', JP: '接続済み', KR: '연결됨', DE: 'Verbunden', FR: 'Connecté', RU: 'Подключено', UA: 'Підключено' },
        'dbNo': { TW: '未連線', CN: '未连接', EN: 'Not connected', JP: '未接続', KR: '연결 안 됨', DE: 'Nicht verbunden', FR: 'Non connecté', RU: 'Не подключено', UA: 'Не підключено' },

        // ── 設定：語言 ───────────────────────────────────────────────
        'langLabel': { TW: '語言', CN: '语言', EN: 'Language', JP: '言語', KR: '언어', DE: 'Sprache', FR: 'Langue', RU: 'Язык', UA: 'Мова' },
        'langNote': { TW: 'Auto: 依 BC TranslationLanguage（CN/TW→中文，其餘→English）', CN: 'Auto: 依 BC TranslationLanguage（CN/TW→中文，其余→English）', EN: 'Auto: follows BC TranslationLanguage (CN/TW→Chinese, others→English)', JP: 'Auto: BC の TranslationLanguage に従う（CN/TW→中国語、他→英語）', KR: 'Auto: BC TranslationLanguage 따름 (CN/TW→중국어, 그 외→영어)', DE: 'Auto: folgt BC TranslationLanguage (CN/TW→Chinesisch, sonst→Englisch)', FR: 'Auto : suit BC TranslationLanguage (CN/TW→chinois, autres→anglais)', RU: 'Авто: по BC TranslationLanguage (CN/TW→китайский, иначе→английский)', UA: 'Авто: за BC TranslationLanguage (CN/TW→китайська, інакше→англійська)' },

        // ── 設定：私聊 / 幽靈 ────────────────────────────────────────
        'whisperIndicatorLabel': { TW: '私聊/BEEP 輸入框提示色', CN: '私聊/BEEP 输入框提示色', EN: 'Whisper/BEEP Input Glow Color', JP: 'ささやき/BEEP 入力欄の枠色', KR: '귓속말/BEEP 입력창 강조 색', DE: 'Flüster-/BEEP-Eingabe-Farbe', FR: 'Couleur de la zone de chuchotement/BEEP', RU: 'Цвет подсветки поля шёпота/BEEP', UA: 'Колір підсвітки поля шепоту/BEEP' },
        'whisperIndicatorNote': { TW: '輸入 /w /whisper /beep 或進入悄悄話模式時，聊天框會顯示紫色邊框提示', CN: '输入 /w /whisper /beep 或进入悄悄话模式时，聊天框会显示紫色边框提示', EN: 'Shows a purple glow on the chat input when /w /whisper /beep is typed or whisper mode is active', JP: '/w /whisper /beep 入力時やささやきモード時に、入力欄へ紫色の枠を表示', KR: '/w /whisper /beep 입력 시 또는 귓속말 모드일 때 입력창에 보라색 테두리 표시', DE: 'Zeigt einen violetten Rand am Chat-Eingabefeld, wenn /w /whisper /beep getippt oder Flüstermodus aktiv ist', FR: 'Affiche un halo violet sur la zone de chat quand /w /whisper /beep est saisi ou en mode chuchotement', RU: 'Показывает фиолетовую рамку поля ввода при вводе /w /whisper /beep или в режиме шёпота', UA: 'Показує фіолетову рамку поля вводу при введенні /w /whisper /beep або в режимі шепоту' },
        'ghostHideLabel': { TW: '幽靈名單隱身', CN: '幽灵名单隐身', EN: 'Ghost List Hide', JP: 'ゴーストリスト非表示', KR: '고스트 목록 숨김', DE: 'Geisterliste ausblenden', FR: 'Masquer liste fantôme', RU: 'Скрытие по списку призраков', UA: 'Приховування за списком привидів' },
        'ghostHideNote': { TW: '幽靈名單中的角色在聊天室不顯示身體（只對自己有效）', CN: '幽灵名单中的角色在聊天室不显示身体（只对自己有效）', EN: 'Characters on your ghost list are hidden in chatroom (only affects your view)', JP: 'ゴーストリストのキャラはチャットルームで非表示（自分の画面のみ）', KR: '고스트 목록의 캐릭터는 채팅방에서 숨겨집니다 (본인 화면에만 적용)', DE: 'Charaktere auf deiner Geisterliste werden im Raum ausgeblendet (nur deine Ansicht)', FR: 'Les personnages de votre liste fantôme sont masqués dans le salon (votre vue seulement)', RU: 'Персонажи из списка призраков скрыты в комнате (только у вас)', UA: 'Персонажі зі списку привидів приховані в кімнаті (лише для вас)' },

        // ── 設定：頭像快取管理 ───────────────────────────────────────
        'btnReloadAvatars': { TW: '頭像快取管理', CN: '头像缓存管理', EN: 'Avatar Cache', JP: 'アバターキャッシュ', KR: '아바타 캐시', DE: 'Avatar-Cache', FR: 'Cache d\'avatars', RU: 'Кэш аватаров', UA: 'Кеш аватарів' },
        'reloadAvatarsNote': { TW: '清除快取或載入好友頭像', CN: '清除缓存或加载好友头像', EN: 'Clear cache or load friend avatars', JP: 'キャッシュ削除またはフレンドのアバター読込', KR: '캐시 삭제 또는 친구 아바타 불러오기', DE: 'Cache leeren oder Freund-Avatare laden', FR: 'Vider le cache ou charger les avatars d\'amis', RU: 'Очистить кэш или загрузить аватары друзей', UA: 'Очистити кеш або завантажити аватари друзів' },
        'btnLoadFriendAvatars': { TW: '載入好友頭像', CN: '加载好友头像', EN: 'Load Friend Avatars', JP: 'フレンドのアバターを読込', KR: '친구 아바타 불러오기', DE: 'Freund-Avatare laden', FR: 'Charger les avatars d\'amis', RU: 'Загрузить аватары друзей', UA: 'Завантажити аватари друзів' },
        'loadFriendAvatarsNote': { TW: '掃描所有好友，讓 BC 緩存外觀後統一截圖（約需數十秒）', CN: '扫描所有好友，让 BC 缓存外观后统一截图（约需数十秒）', EN: 'Scan all friends, wait for BC to cache appearances, then snapshot (may take tens of seconds)', JP: '全フレンドをスキャンし、BC が外見をキャッシュしてから一括撮影（数十秒かかる場合あり）', KR: '모든 친구를 스캔하고 BC가 외형을 캐시한 뒤 일괄 촬영 (수십 초 소요될 수 있음)', DE: 'Alle Freunde scannen, auf BC-Cache warten, dann Schnappschuss (kann Sekunden dauern)', FR: 'Analyser tous les amis, attendre le cache BC, puis capturer (peut prendre des dizaines de secondes)', RU: 'Сканировать всех друзей, дождаться кэша BC, затем снимок (может занять десятки секунд)', UA: 'Сканувати всіх друзів, дочекатися кешу BC, потім знімок (може зайняти десятки секунд)' },
        'btnClearAvatarCache': { TW: '清除頭像快取', CN: '清除头像缓存', EN: 'Clear Avatar Cache', JP: 'アバターキャッシュを削除', KR: '아바타 캐시 삭제', DE: 'Avatar-Cache leeren', FR: 'Vider le cache d\'avatars', RU: 'Очистить кэш аватаров', UA: 'Очистити кеш аватарів' },
        'clearAvatarCacheNote': { TW: '清除所有已儲存的頭像快照，下次遇到時重新截取', CN: '清除所有已保存的头像快照，下次遇到时重新截取', EN: 'Delete all saved avatar snapshots — new ones will be captured on next encounter', JP: '保存済みのアバターを全削除。次回遭遇時に再取得', KR: '저장된 아바타 스냅샷 모두 삭제 — 다음에 만나면 다시 캡처', DE: 'Alle gespeicherten Avatar-Schnappschüsse löschen — neue bei nächster Begegnung', FR: 'Supprimer tous les avatars enregistrés — recapturés à la prochaine rencontre', RU: 'Удалить все сохранённые снимки аватаров — новые при следующей встрече', UA: 'Видалити всі збережені знімки аватарів — нові при наступній зустрічі' },
        'loadFriendAvatarsDone': { TW: '好友頭像載入完成', CN: '好友头像加载完成', EN: 'Friend avatar loading complete', JP: 'フレンドのアバター読込完了', KR: '친구 아바타 불러오기 완료', DE: 'Laden der Freund-Avatare abgeschlossen', FR: 'Chargement des avatars d\'amis terminé', RU: 'Загрузка аватаров друзей завершена', UA: 'Завантаження аватарів друзів завершено' },
        'loadingFriendAvatars': { TW: '載入好友頭像中... 剩餘 {0} 人', CN: '加载好友头像中... 剩余 {0} 人', EN: 'Loading friend avatars... {0} remaining', JP: 'フレンドのアバター読込中... 残り {0} 人', KR: '친구 아바타 불러오는 중... {0}명 남음', DE: 'Lade Freund-Avatare... {0} übrig', FR: 'Chargement des avatars... {0} restant(s)', RU: 'Загрузка аватаров... осталось {0}', UA: 'Завантаження аватарів... залишилось {0}' },

        // ── 確認對話 ─────────────────────────────────────────────────
        'noProfile': { TW: '尚無個人資料\n（需先與此人在同一房間）', CN: '尚无个人资料\n（需先与此人在同一房间）', EN: 'No profile data\n(Must have been in same room)', JP: 'プロフィールデータなし\n（同じルームにいた必要あり）', KR: '프로필 데이터 없음\n(같은 방에 있었어야 함)', DE: 'Keine Profildaten\n(Muss im selben Raum gewesen sein)', FR: 'Aucune donnée de profil\n(Doit avoir été dans le même salon)', RU: 'Нет данных профиля\n(Нужно было быть в одной комнате)', UA: 'Немає даних профілю\n(Потрібно було бути в одній кімнаті)' },
        'confirmDel': { TW: '確定刪除好友「{0}」？', CN: '确定删除好友「{0}」？', EN: 'Unfriend "{0}"?', JP: '「{0}」をフレンド解除しますか？', KR: '"{0}" 친구를 삭제할까요?', DE: '„{0}" entfreunden?', FR: 'Retirer « {0} » des amis ?', RU: 'Удалить «{0}» из друзей?', UA: 'Видалити «{0}» з друзів?' },
        'confirmKick': { TW: '確定逐出「{0}」？', CN: '确定逐出「{0}」？', EN: 'Kick "{0}"?', JP: '「{0}」をキックしますか？', KR: '"{0}"을(를) 추방할까요?', DE: '„{0}" kicken?', FR: 'Expulser « {0} » ?', RU: 'Выгнать «{0}»?', UA: 'Вигнати «{0}»?' },
        'confirmRoom': { TW: '🚪 前往房間「{0}」？', CN: '🚪 前往房间「{0}」？', EN: '🚪 Go to room "{0}"?', JP: '🚪 ルーム「{0}」へ移動しますか？', KR: '🚪 "{0}" 방으로 이동할까요?', DE: '🚪 Zum Raum „{0}" gehen?', FR: '🚪 Aller au salon « {0} » ?', RU: '🚪 Перейти в комнату «{0}»?', UA: '🚪 Перейти до кімнати «{0}»?' },
        'confirmAddBan': { TW: '確定將「{0}」加入黑名單？\n對方將無法與你互動。', CN: '确定将「{0}」加入黑名单？\n对方将无法与你互动。', EN: 'Blacklist "{0}"?\nThey will no longer be able to interact with you.', JP: '「{0}」をブラックリストに追加しますか？\n相手はあなたと交流できなくなります。', KR: '"{0}"을(를) 블랙리스트에 추가할까요?\n상대는 더 이상 당신과 상호작용할 수 없습니다.', DE: '„{0}" auf die Blacklist setzen?\nDiese Person kann nicht mehr mit dir interagieren.', FR: 'Mettre « {0} » sur liste noire ?\nCette personne ne pourra plus interagir avec vous.', RU: 'Добавить «{0}» в чёрный список?\nОн больше не сможет взаимодействовать с вами.', UA: 'Додати «{0}» до чорного списку?\nВін більше не зможе взаємодіяти з вами.' },
        'confirmAddGhost': { TW: '確定將「{0}」加入幽靈名單？\n你將不會再收到任何該玩家的信息。', CN: '确定将「{0}」加入幽灵名单？\n你将不会再收到任何该玩家的信息。', EN: 'Add "{0}" to ghost list?\nYou will no longer receive any messages from that person.', JP: '「{0}」をゴーストリストに追加しますか？\nこの相手からのメッセージは一切届かなくなります。', KR: '"{0}"을(를) 고스트 목록에 추가할까요?\n해당 플레이어의 메시지를 더 이상 받지 않습니다.', DE: '„{0}" zur Geisterliste hinzufügen?\nDu erhältst keine Nachrichten mehr von dieser Person.', FR: 'Ajouter « {0} » à la liste fantôme ?\nVous ne recevrez plus aucun message de cette personne.', RU: 'Добавить «{0}» в список призраков?\nВы больше не будете получать от него сообщений.', UA: 'Додати «{0}» до списку привидів?\nВи більше не отримуватимете від нього повідомлень.' },

        // ── 房間搜尋 ─────────────────────────────────────────────────
        'tabRoomSearch': { TW: '查詢房間', CN: '查询房间', EN: 'Search Rooms', JP: 'ルーム検索', KR: '방 검색', DE: 'Räume suchen', FR: 'Chercher salons', RU: 'Поиск комнат', UA: 'Пошук кімнат' },
        'roomSearch2': { TW: '搜尋房間...', CN: '搜索房间...', EN: 'Search rooms...', JP: 'ルームを検索...', KR: '방 검색...', DE: 'Räume suchen...', FR: 'Chercher des salons...', RU: 'Поиск комнат...', UA: 'Пошук кімнат...' },
        'roomSearchBtn': { TW: '搜尋', CN: '搜索', EN: 'Search', JP: '検索', KR: '검색', DE: 'Suchen', FR: 'Chercher', RU: 'Поиск', UA: 'Пошук' },
        'roomSearching': { TW: '搜尋中...', CN: '搜索中...', EN: 'Searching...', JP: '検索中...', KR: '검색 중...', DE: 'Suche...', FR: 'Recherche...', RU: 'Поиск...', UA: 'Пошук...' },
        'roomSearchEmpty': { TW: '沒有找到房間', CN: '没有找到房间', EN: 'No rooms found', JP: 'ルームが見つかりません', KR: '방을 찾을 수 없음', DE: 'Keine Räume gefunden', FR: 'Aucun salon trouvé', RU: 'Комнаты не найдены', UA: 'Кімнат не знайдено' },
        'roomFavLabel': { TW: '★ 最愛', CN: '★ 最爱', EN: '★ Favs', JP: '★ お気に入り', KR: '★ 즐겨찾기', DE: '★ Favoriten', FR: '★ Favoris', RU: '★ Избранное', UA: '★ Обране' },
        'roomJoin': { TW: '加入', CN: '加入', EN: 'Join', JP: '参加', KR: '입장', DE: 'Beitreten', FR: 'Rejoindre', RU: 'Войти', UA: 'Приєднатися' },
        'roomMixed': { TW: '混合', CN: '混合', EN: 'Mixed', JP: '混合', KR: '혼합', DE: 'Gemischt', FR: 'Mixte', RU: 'Смешанная', UA: 'Змішана' },
        'roomFemale': { TW: '女性', CN: '女性', EN: 'Female', JP: '女性', KR: '여성', DE: 'Weiblich', FR: 'Féminin', RU: 'Женская', UA: 'Жіноча' },
        'roomMale': { TW: '男性', CN: '男性', EN: 'Male', JP: '男性', KR: '남성', DE: 'Männlich', FR: 'Masculin', RU: 'Мужская', UA: 'Чоловіча' },
        'totalRooms': { TW: '共 {0} 間', CN: '共 {0} 间', EN: 'Rooms: {0}', JP: 'ルーム: {0}', KR: '방: {0}', DE: 'Räume: {0}', FR: 'Salons : {0}', RU: 'Комнат: {0}', UA: 'Кімнат: {0}' },
        'roomPrivateLabel': { TW: '私人', CN: '私人', EN: 'Private', JP: 'プライベート', KR: '비공개', DE: 'Privat', FR: 'Privé', RU: 'Приватная', UA: 'Приватна' },

        // ── 房間權限 ─────────────────────────────────────────────────
        'permAdmin': { TW: '管理', CN: '管理', EN: 'Admin', JP: '管理', KR: '관리', DE: 'Admin', FR: 'Admin', RU: 'Админ', UA: 'Адмін' },
        'permPass': { TW: 'PASS', CN: 'PASS', EN: 'PASS', JP: 'PASS', KR: 'PASS', DE: 'PASS', FR: 'PASS', RU: 'PASS', UA: 'PASS' },
        'permBan': { TW: 'BAN', CN: 'BAN', EN: 'BAN', JP: 'BAN', KR: 'BAN', DE: 'BANN', FR: 'BAN', RU: 'БАН', UA: 'БАН' },
        'permVisit': { TW: '訪客', CN: '访客', EN: 'Visit', JP: '訪問者', KR: '방문자', DE: 'Gast', FR: 'Visiteur', RU: 'Гость', UA: 'Гість' },
        'youLabel': { TW: '（你）', CN: '（你）', EN: '(You)', JP: '（あなた）', KR: '(당신)', DE: '(Du)', FR: '(Vous)', RU: '(Вы)', UA: '(Ви)' },
        'copyId': { TW: '點擊複製ID', CN: '点击复制ID', EN: 'Click to copy ID', JP: 'クリックでIDをコピー', KR: '클릭하여 ID 복사', DE: 'Klicken zum Kopieren der ID', FR: 'Cliquer pour copier l\'ID', RU: 'Нажмите, чтобы скопировать ID', UA: 'Натисніть, щоб скопіювати ID' },
        'copyDone': { TW: '已複製！', CN: '已复制！', EN: 'Copied!', JP: 'コピーしました！', KR: '복사됨!', DE: 'Kopiert!', FR: 'Copié !', RU: 'Скопировано!', UA: 'Скопійовано!' },
        'total': { TW: '共 {0} 人', CN: '共 {0} 人', EN: 'Total: {0}', JP: '合計: {0}人', KR: '총: {0}명', DE: 'Gesamt: {0}', FR: 'Total : {0}', RU: 'Всего: {0}', UA: 'Всього: {0}' },

        // ── BEEP 視窗 ────────────────────────────────────────────────
        'beepTitle': { TW: 'BEEP → {0}', CN: 'BEEP → {0}', EN: 'BEEP → {0}', JP: 'BEEP → {0}', KR: 'BEEP → {0}', DE: 'BEEP → {0}', FR: 'BEEP → {0}', RU: 'BEEP → {0}', UA: 'BEEP → {0}' },
        'beepPlaceholder': { TW: '輸入訊息（可留空）\nCtrl+Enter 發送', CN: '输入消息（可留空）\nCtrl+Enter 发送', EN: 'Type message (can be empty)\nCtrl+Enter to send', JP: 'メッセージを入力（空でも可）\nCtrl+Enter で送信', KR: '메시지 입력 (비워도 됨)\nCtrl+Enter로 전송', DE: 'Nachricht eingeben (optional)\nStrg+Enter zum Senden', FR: 'Tapez un message (facultatif)\nCtrl+Entrée pour envoyer', RU: 'Введите сообщение (можно пусто)\nCtrl+Enter для отправки', UA: 'Введіть повідомлення (можна порожнє)\nCtrl+Enter для надсилання' },
        'beepSend': { TW: '發送 BEEP', CN: '发送 BEEP', EN: 'Send BEEP', JP: 'BEEP を送信', KR: 'BEEP 전송', DE: 'BEEP senden', FR: 'Envoyer BEEP', RU: 'Отправить BEEP', UA: 'Надіслати BEEP' },
        'beepCancel': { TW: '取消', CN: '取消', EN: 'Cancel', JP: 'キャンセル', KR: '취소', DE: 'Abbrechen', FR: 'Annuler', RU: 'Отмена', UA: 'Скасувати' },
        'beepSummon': { TW: '召喚', CN: '召唤', EN: 'Summon', JP: '召喚', KR: '소환', DE: 'Rufen', FR: 'Convoquer', RU: 'Призвать', UA: 'Викликати' },
        'beepSummonTitle': { TW: '請確定您有召喚對方的權限，否則對方只會收到 summon', CN: '请确定您有召唤对方的权限，否则对方只会收到 summon', EN: 'You must have the authority to summon the other player.\nOtherwise, they will only receive "summon".', JP: '相手を召喚する権限が必要です。\nなければ相手には「summon」という文字だけが届きます。', KR: '상대를 소환할 권한이 있어야 합니다.\n없으면 상대는 "summon" 텍스트만 받습니다.', DE: 'Du benötigst die Berechtigung, den anderen Spieler zu rufen.\nSonst erhält er nur „summon".', FR: 'Vous devez avoir l\'autorité pour convoquer l\'autre joueur.\nSinon, il ne recevra que « summon ».', RU: 'У вас должно быть право призывать другого игрока.\nИначе он получит только «summon».', UA: 'Ви повинні мати право викликати іншого гравця.\nІнакше він отримає лише «summon».' },
        'beepSummonNoRoom': { TW: '需在房間內才能召喚', CN: '需在房间内才能召唤', EN: 'Must be in a room to summon', JP: '召喚するにはルーム内にいる必要があります', KR: '소환하려면 방 안에 있어야 합니다', DE: 'Zum Rufen musst du in einem Raum sein', FR: 'Il faut être dans un salon pour convoquer', RU: 'Для призыва нужно быть в комнате', UA: 'Для виклику потрібно бути в кімнаті' },
        'noData': { TW: '（空白）', CN: '（空白）', EN: '(Empty)', JP: '（空）', KR: '(비어 있음)', DE: '(Leer)', FR: '(Vide)', RU: '(Пусто)', UA: '(Порожньо)' },
        'noFriends': { TW: '沒有符合條件的好友', CN: '没有符合条件的好友', EN: 'No matching entries', JP: '条件に合う項目がありません', KR: '일치하는 항목 없음', DE: 'Keine passenden Einträge', FR: 'Aucune entrée correspondante', RU: 'Нет подходящих записей', UA: 'Немає відповідних записів' },
        'fWhitelist': { TW: '白名單', CN: '白名单', EN: 'Whitelist', JP: 'ホワイトリスト', KR: '화이트리스트', DE: 'Whitelist', FR: 'Liste blanche', RU: 'Белый список', UA: 'Білий список' },
        'fBlacklist': { TW: '黑名單', CN: '黑名单', EN: 'Blacklist', JP: 'ブラックリスト', KR: '블랙리스트', DE: 'Blacklist', FR: 'Liste noire', RU: 'Чёрный список', UA: 'Чорний список' },
        'fGhost': { TW: '幽靈', CN: '幽灵', EN: 'Ghost', JP: 'ゴースト', KR: '고스트', DE: 'Geist', FR: 'Fantôme', RU: 'Призрак', UA: 'Привид' },
        'roomPrivate': { TW: '私人', CN: '私人', EN: 'Private', JP: 'プライベート', KR: '비공개', DE: 'Privat', FR: 'Privé', RU: 'Приватная', UA: 'Приватна' },
        'roomPublic': { TW: '', CN: '', EN: '', JP: '', KR: '', DE: '', FR: '', RU: '', UA: '' },

        // ── 設定：儲存模式 ───────────────────────────────────────────
        'saveModeLabel': { TW: '儲存模式', CN: '保存模式', EN: 'Save Mode', JP: '保存モード', KR: '저장 모드', DE: 'Speichermodus', FR: 'Mode d\'enregistrement', RU: 'Режим сохранения', UA: 'Режим збереження' },
        'saveModeOff': { TW: '不儲存', CN: '不保存', EN: 'Off', JP: '保存しない', KR: '저장 안 함', DE: 'Aus', FR: 'Désactivé', RU: 'Выкл.', UA: 'Вимк.' },
        'saveModeName': { TW: '僅名稱', CN: '仅名称', EN: 'Name only', JP: '名前のみ', KR: '이름만', DE: 'Nur Name', FR: 'Nom seul', RU: 'Только имя', UA: 'Лише ім\'я' },
        'saveModeAvatar': { TW: '名稱與頭像', CN: '名称与头像', EN: 'Name + Avatar', JP: '名前＋アバター', KR: '이름＋아바타', DE: 'Name + Avatar', FR: 'Nom + avatar', RU: 'Имя + аватар', UA: 'Ім\'я + аватар' },
        'saveModeFull': { TW: '完整資料（WCE 相容）', CN: '完整资料（WCE 兼容）', EN: 'Full profile (WCE)', JP: '完全プロフィール（WCE）', KR: '전체 프로필 (WCE)', DE: 'Vollständiges Profil (WCE)', FR: 'Profil complet (WCE)', RU: 'Полный профиль (WCE)', UA: 'Повний профіль (WCE)' },
        'saveModeDesc_off': { TW: '不儲存任何資料。如果你有安裝 WCE 並啟用其 Profiles 功能，建議選此選項避免重複儲存（WCE 已幫你存好了）。', CN: '不保存任何资料。如果你有安装 WCE 并启用其 Profiles 功能，建议选此选项避免重复保存（WCE 已帮你存好了）。', EN: "Don't save any data. If you have WCE with Profiles enabled, choose this to avoid duplicates (WCE already saves for you).", JP: 'データを一切保存しません。WCE の Profiles 機能を有効にしている場合は、重複を避けるためこれを選択（WCE が保存済み）。', KR: '어떤 데이터도 저장하지 않습니다. WCE의 Profiles 기능을 사용 중이면 중복을 피하기 위해 이 옵션 권장 (WCE가 이미 저장함).', DE: 'Keine Daten speichern. Wenn WCE mit Profilen aktiv ist, wähle dies, um Duplikate zu vermeiden (WCE speichert bereits).', FR: 'Ne rien enregistrer. Si WCE avec Profils est activé, choisissez ceci pour éviter les doublons (WCE enregistre déjà).', RU: 'Ничего не сохранять. Если у вас WCE с профилями, выберите это, чтобы избежать дублей (WCE уже сохраняет).', UA: 'Нічого не зберігати. Якщо у вас WCE з профілями, оберіть це, щоб уникнути дублів (WCE вже зберігає).' },
        'saveModeDesc_name': { TW: '只儲存成員編號、BC 名稱、暱稱。幾乎不佔空間，可用來顯示離線好友名稱。', CN: '只保存成员编号、BC 名称、昵称。几乎不占空间，可用来显示离线好友名称。', EN: 'Save member number, BC name, and nickname only. Minimal space, used for displaying offline friend names.', JP: 'メンバー番号・BC 名・ニックネームのみ保存。容量ほぼ不要、オフラインのフレンド名表示に使用。', KR: '멤버 번호, BC 이름, 닉네임만 저장. 용량 거의 없음, 오프라인 친구 이름 표시에 사용.', DE: 'Nur Mitgliedsnummer, BC-Name und Spitzname speichern. Minimal, zeigt Namen von Offline-Freunden.', FR: 'Enregistrer seulement le numéro, le nom BC et le surnom. Peu d\'espace, affiche les noms d\'amis hors ligne.', RU: 'Сохранять только номер, имя BC и никнейм. Минимум места, для имён офлайн-друзей.', UA: 'Зберігати лише номер, ім\'я BC і нікнейм. Мінімум місця, для імен офлайн-друзів.' },
        'saveModeDesc_avatar': { TW: '額外儲存頭像快照（在遇見時自動擷取，儲存於獨立的 FCM-Snapshot 資料庫）。', CN: '额外保存头像快照（在遇见时自动截取，保存于独立的 FCM-Snapshot 数据库）。', EN: 'Also save avatar snapshot (auto-captured when encountered, stored in separate FCM-Snapshot DB).', JP: 'アバターのスナップショットも保存（遭遇時に自動取得、独立の FCM-Snapshot DB に格納）。', KR: '아바타 스냅샷도 저장 (만났을 때 자동 캡처, 별도의 FCM-Snapshot DB에 보관).', DE: 'Zusätzlich Avatar-Schnappschuss speichern (bei Begegnung erfasst, in separater FCM-Snapshot-DB).', FR: 'Enregistrer aussi l\'avatar (capturé lors d\'une rencontre, dans une BD FCM-Snapshot séparée).', RU: 'Также сохранять снимок аватара (при встрече, в отдельной БД FCM-Snapshot).', UA: 'Також зберігати знімок аватара (при зустрічі, в окремій БД FCM-Snapshot).' },
        'saveModeDesc_full': { TW: '完整儲存：名稱、暱稱、外觀/BIO/稱號等。與 WCE bce-past-profiles 資料庫完全相容，互相共用。頭像另存於 FCM-Snapshot。', CN: '完整保存：名称、昵称、外观/BIO/称号等。与 WCE bce-past-profiles 数据库完全兼容，互相共用。头像另存于 FCM-Snapshot。', EN: 'Full save: name, nickname, appearance/BIO/title etc. Fully compatible with WCE bce-past-profiles DB. Avatars stored separately in FCM-Snapshot.', JP: '完全保存：名前・ニックネーム・外見/BIO/称号など。WCE bce-past-profiles DB と完全互換で共用。アバターは FCM-Snapshot に別保存。', KR: '전체 저장: 이름, 닉네임, 외형/BIO/칭호 등. WCE bce-past-profiles DB와 완전 호환·공유. 아바타는 FCM-Snapshot에 별도 저장.', DE: 'Vollständig: Name, Spitzname, Aussehen/BIO/Titel usw. Voll kompatibel mit WCE bce-past-profiles-DB. Avatare separat in FCM-Snapshot.', FR: 'Complet : nom, surnom, apparence/BIO/titre, etc. Totalement compatible avec la BD WCE bce-past-profiles. Avatars stockés dans FCM-Snapshot.', RU: 'Полностью: имя, ник, внешность/BIO/титул и т.д. Полная совместимость с БД WCE bce-past-profiles. Аватары — в FCM-Snapshot.', UA: 'Повністю: ім\'я, нік, зовнішність/BIO/титул тощо. Повна сумісність з БД WCE bce-past-profiles. Аватари — у FCM-Snapshot.' },
        'wceDetected': { TW: '✅ 偵測到 WCE Profiles 功能，已自動設為完整資料模式（與 WCE 共用同一個 DB，避免衝突）', CN: '✅ 检测到 WCE Profiles 功能，已自动设为完整资料模式（与 WCE 共用同一个 DB，避免冲突）', EN: '✅ WCE Profiles detected — auto-set to Full mode (shared DB, no conflicts)', JP: '✅ WCE Profiles を検出 — 完全モードに自動設定（DB を共用、競合なし）', KR: '✅ WCE Profiles 감지됨 — 전체 모드로 자동 설정 (DB 공유, 충돌 없음)', DE: '✅ WCE-Profile erkannt — automatisch auf Vollmodus gesetzt (gemeinsame DB, keine Konflikte)', FR: '✅ Profils WCE détectés — mode Complet auto (BD partagée, sans conflit)', RU: '✅ Обнаружены профили WCE — авто-режим «Полный» (общая БД, без конфликтов)', UA: '✅ Виявлено профілі WCE — авто-режим «Повний» (спільна БД, без конфліктів)' },
        'wceNotDetected': { TW: '未偵測到 WCE。建議若只需顯示名稱則選「僅名稱」，需要頭像則選「名稱與頭像」。', CN: '未检测到 WCE。建议若只需显示名称则选「仅名称」，需要头像则选「名称与头像」。', EN: 'WCE not detected. Use Name-only for minimal storage, or Name+Avatar if you want portraits.', JP: 'WCE 未検出。名前だけなら「名前のみ」、アバターが欲しければ「名前＋アバター」を推奨。', KR: 'WCE 미감지. 이름만 필요하면 「이름만」, 아바타가 필요하면 「이름＋아바타」 권장.', DE: 'WCE nicht erkannt. „Nur Name" für minimalen Speicher, „Name+Avatar" für Porträts.', FR: 'WCE non détecté. « Nom seul » pour un stockage minimal, « Nom+avatar » pour les portraits.', RU: 'WCE не обнаружен. «Только имя» для минимума, «Имя+аватар» для портретов.', UA: 'WCE не виявлено. «Лише ім\'я» для мінімуму, «Ім\'я+аватар» для портретів.' },

        // ── 匯出 / 匯入 ──────────────────────────────────────────────
        'exportProfiles': { TW: '匯出 Profiles', CN: '导出 Profiles', EN: 'Export Profiles', JP: 'Profiles をエクスポート', KR: 'Profiles 내보내기', DE: 'Profile exportieren', FR: 'Exporter les profils', RU: 'Экспорт профилей', UA: 'Експорт профілів' },
        'exportNote': { TW: '匯出為 JSON（與 WCE 格式相容）', CN: '导出为 JSON（与 WCE 格式兼容）', EN: 'Export as JSON (WCE-compatible format)', JP: 'JSON でエクスポート（WCE 形式互換）', KR: 'JSON으로 내보내기 (WCE 형식 호환)', DE: 'Als JSON exportieren (WCE-kompatibel)', FR: 'Exporter en JSON (compatible WCE)', RU: 'Экспорт в JSON (совместим с WCE)', UA: 'Експорт у JSON (сумісно з WCE)' },
        'importProfiles': { TW: '匯入 Profiles', CN: '导入 Profiles', EN: 'Import Profiles', JP: 'Profiles をインポート', KR: 'Profiles 가져오기', DE: 'Profile importieren', FR: 'Importer les profils', RU: 'Импорт профилей', UA: 'Імпорт профілів' },
        'importNote': { TW: '從 JSON 匯入（相同 ID 以較新的 seen 時間為準）', CN: '从 JSON 导入（相同 ID 以较新的 seen 时间为准）', EN: 'Import from JSON (newer seen timestamp wins on conflict)', JP: 'JSON からインポート（同一 ID は seen が新しい方を採用）', KR: 'JSON에서 가져오기 (동일 ID는 더 최신 seen 우선)', DE: 'Aus JSON importieren (bei Konflikt gewinnt neuerer Zeitstempel)', FR: 'Importer depuis JSON (le plus récent l\'emporte en cas de conflit)', RU: 'Импорт из JSON (при конфликте побеждает более новая метка)', UA: 'Імпорт з JSON (при конфлікті перемагає новіша мітка)' },
        'exportDone': { TW: '✓ 已匯出 {0} 筆 profiles', CN: '✓ 已导出 {0} 条 profiles', EN: '✓ Exported {0} profiles', JP: '✓ {0} 件の profiles をエクスポート', KR: '✓ {0}개의 profiles 내보냄', DE: '✓ {0} Profile exportiert', FR: '✓ {0} profils exportés', RU: '✓ Экспортировано профилей: {0}', UA: '✓ Експортовано профілів: {0}' },

        // ── Profiles 列表 ────────────────────────────────────────────
        'profilesTitle': { TW: '已儲存的 Profiles', CN: '已保存的 Profiles', EN: 'Saved Profiles', JP: '保存済み Profiles', KR: '저장된 Profiles', DE: 'Gespeicherte Profile', FR: 'Profils enregistrés', RU: 'Сохранённые профили', UA: 'Збережені профілі' },
        'profilesHint': { TW: '點擊開啟角色資訊', CN: '点击打开角色信息', EN: 'Click to open character info', JP: 'クリックでキャラ情報を開く', KR: '클릭하여 캐릭터 정보 열기', DE: 'Klicken für Charakter-Info', FR: 'Cliquer pour ouvrir la fiche', RU: 'Нажмите, чтобы открыть профиль', UA: 'Натисніть, щоб відкрити профіль' },
        'profilesEmpty': { TW: '沒有符合條件的 profiles', CN: '没有符合条件的 profiles', EN: 'No matching profiles', JP: '条件に合う profiles がありません', KR: '일치하는 profiles 없음', DE: 'Keine passenden Profile', FR: 'Aucun profil correspondant', RU: 'Нет подходящих профилей', UA: 'Немає відповідних профілів' },
        'profilesTotal': { TW: '顯示 {0} / 共 {1} 筆', CN: '显示 {0} / 共 {1} 条', EN: 'Showing {0} of {1}', JP: '{1} 件中 {0} 件を表示', KR: '{1}개 중 {0}개 표시', DE: 'Zeige {0} von {1}', FR: 'Affichage de {0} sur {1}', RU: 'Показано {0} из {1}', UA: 'Показано {0} з {1}' },
        'searchProfiles': { TW: '搜尋名稱或ID...', CN: '搜索名称或ID...', EN: 'Search name or ID...', JP: '名前かIDを検索...', KR: '이름 또는 ID 검색...', DE: 'Name oder ID suchen...', FR: 'Chercher nom ou ID...', RU: 'Поиск по имени или ID...', UA: 'Пошук за іменем або ID...' },

        // ── 人員查詢 ─────────────────────────────────────────────────
        'peopleSearchPlaceholder': { TW: '輸入名稱或 ID，按 Enter 搜尋...', CN: '输入名称或 ID，按 Enter 搜索...', EN: 'Name or ID — press Enter to search...', JP: '名前かID — Enter で検索...', KR: '이름 또는 ID — Enter로 검색...', DE: 'Name oder ID — Enter zum Suchen...', FR: 'Nom ou ID — Entrée pour chercher...', RU: 'Имя или ID — Enter для поиска...', UA: 'Ім\'я або ID — Enter для пошуку...' },
        'peopleSearchHint': { TW: '顯示最近見過的 100 人 · 輸入後按 Enter 或點「搜尋」', CN: '显示最近见过的 100 人 · 输入后按 Enter 或点「搜索」', EN: 'Showing last 100 encountered · type then press Enter or click Search', JP: '直近に遭遇した 100 人を表示 · 入力後 Enter か「検索」', KR: '최근 만난 100명 표시 · 입력 후 Enter 또는 「검색」', DE: 'Zeigt die letzten 100 Begegnungen · tippen und Enter oder Suchen klicken', FR: 'Affiche les 100 dernières rencontres · saisir puis Entrée ou cliquer Chercher', RU: 'Показаны последние 100 встреч · введите и нажмите Enter или «Поиск»', UA: 'Показано останні 100 зустрічей · введіть і натисніть Enter або «Пошук»' },
        'peopleNoResults': { TW: '沒有找到符合的人員', CN: '没有找到符合的人员', EN: 'No matching people found', JP: '条件に合う人物が見つかりません', KR: '일치하는 인물을 찾을 수 없음', DE: 'Keine passenden Personen gefunden', FR: 'Aucune personne correspondante', RU: 'Подходящих людей не найдено', UA: 'Відповідних людей не знайдено' },
        'peopleUnknownId': { TW: '請問您是否在搜尋 #{0}？你並無該人員資料', CN: '请问您是否在搜索 #{0}？你并无该人员资料', EN: 'Did you mean #{0}? No record found for this ID.', JP: '#{0} をお探しですか？このIDのデータはありません。', KR: '#{0}을(를) 찾으시나요? 이 ID의 기록이 없습니다.', DE: 'Meintest du #{0}? Kein Eintrag für diese ID gefunden.', FR: 'Vouliez-vous dire #{0} ? Aucun enregistrement pour cet ID.', RU: 'Вы искали #{0}? Записей для этого ID не найдено.', UA: 'Ви шукали #{0}? Записів для цього ID не знайдено.' },
        'peopleSimilarIds': { TW: '包含此數字的相似 ID：', CN: '包含此数字的相似 ID：', EN: 'Similar IDs containing this number:', JP: 'この数字を含む類似 ID：', KR: '이 숫자를 포함한 유사 ID:', DE: 'Ähnliche IDs mit dieser Zahl:', FR: 'ID similaires contenant ce nombre :', RU: 'Похожие ID с этим числом:', UA: 'Схожі ID з цим числом:' },
        'peopleUnknownName': { TW: '名稱未知', CN: '名称未知', EN: 'Name unknown', JP: '名前不明', KR: '이름 미상', DE: 'Name unbekannt', FR: 'Nom inconnu', RU: 'Имя неизвестно', UA: 'Ім\'я невідоме' },
        'peopleOneSidedWarn': { TW: '⚠ 提醒：此操作為單方面添加。如果有需要，請您主動通知對方。', CN: '⚠ 提醒：此操作为单方面添加。如果有需要，请您主动通知对方。', EN: '⚠ Note: This action is a one-way addition. If necessary, please notify the other party yourself.', JP: '⚠ 注意：この操作は一方的な追加です。必要なら相手にご自身で通知してください。', KR: '⚠ 참고: 이 작업은 일방적 추가입니다. 필요하면 상대에게 직접 알려주세요.', DE: '⚠ Hinweis: Dies ist eine einseitige Aktion. Bei Bedarf informiere die andere Person selbst.', FR: '⚠ Note : action unilatérale. Si nécessaire, prévenez l\'autre personne vous-même.', RU: '⚠ Внимание: это одностороннее добавление. При необходимости уведомите другого сами.', UA: '⚠ Увага: це одностороннє додавання. За потреби повідомте іншого самі.' },
        'peopleTotal': { TW: '顯示 {0} / 共 {1} 筆', CN: '显示 {0} / 共 {1} 条', EN: 'Showing {0} of {1}', JP: '{1} 件中 {0} 件を表示', KR: '{1}개 중 {0}개 표시', DE: 'Zeige {0} von {1}', FR: 'Affichage de {0} sur {1}', RU: 'Показано {0} из {1}', UA: 'Показано {0} з {1}' },

        // ── 分享 ─────────────────────────────────────────────────────
        'colShare': { TW: '分享', CN: '分享', EN: 'Share', JP: '共有', KR: '공유', DE: 'Teilen', FR: 'Partager', RU: 'Поделиться', UA: 'Поділитися' },
        'btnShare': { TW: '分享', CN: '分享', EN: 'Share', JP: '共有', KR: '공유', DE: 'Teilen', FR: 'Partager', RU: 'Поделиться', UA: 'Поділитися' },
        'shareLocalMsg': { TW: '📜 已分享 {0} ({1}) 的 Profile', CN: '📜 已分享 {0} ({1}) 的 Profile', EN: '📜 Shared profile: {0} ({1})', JP: '📜 {0} ({1}) の Profile を共有しました', KR: '📜 {0} ({1})의 Profile을 공유함', DE: '📜 Profil geteilt: {0} ({1})', FR: '📜 Profil partagé : {0} ({1})', RU: '📜 Профиль отправлен: {0} ({1})', UA: '📜 Профіль надіслано: {0} ({1})' },
        'shareRecvMsg': { TW: '📜 {0} 分享了 {1} 保存於: {2}', CN: '📜 {0} 分享了 {1} 保存于: {2}', EN: '📜 {0} shared a profile: {1} saved: {2}', JP: '📜 {0} が Profile を共有: {1} 保存日: {2}', KR: '📜 {0}님이 프로필 공유: {1} 저장일: {2}', DE: '📜 {0} teilte ein Profil: {1} gespeichert: {2}', FR: '📜 {0} a partagé un profil : {1} enregistré : {2}', RU: '📜 {0} поделился профилем: {1} сохранён: {2}', UA: '📜 {0} поділився профілем: {1} збережено: {2}' },
        'shareOpen': { TW: '▶ 開啟', CN: '▶ 打开', EN: '▶ Open', JP: '▶ 開く', KR: '▶ 열기', DE: '▶ Öffnen', FR: '▶ Ouvrir', RU: '▶ Открыть', UA: '▶ Відкрити' },

        // ── 設定：私聊頭像 / OOC / 按鈕顯示 ─────────────────────────
        'whisperAvatarLabel': { TW: '私聊時顯示對象頭像', CN: '私聊时显示对象头像', EN: 'Show target avatar during whisper', JP: 'ささやき時に相手のアバターを表示', KR: '귓속말 시 대상 아바타 표시', DE: 'Ziel-Avatar beim Flüstern zeigen', FR: 'Afficher l\'avatar de la cible en chuchotement', RU: 'Показывать аватар при шёпоте', UA: 'Показувати аватар при шепоті' },
        'whisperAvatarNote': { TW: '進入悄悄話/BEEP 模式時，在輸入框旁顯示對象的頭像', CN: '进入悄悄话/BEEP 模式时，在输入框旁显示对象的头像', EN: "Displays the target's avatar near the chat input when in whisper/BEEP mode", JP: 'ささやき/BEEP モード時、入力欄の横に相手のアバターを表示', KR: '귓속말/BEEP 모드일 때 입력창 옆에 대상 아바타 표시', DE: 'Zeigt den Avatar des Ziels neben der Eingabe im Flüster-/BEEP-Modus', FR: "Affiche l'avatar de la cible près de la saisie en mode chuchotement/BEEP", RU: 'Показывает аватар цели рядом с полем ввода в режиме шёпота/BEEP', UA: 'Показує аватар цілі біля поля вводу в режимі шепоту/BEEP' },
        'oocProtectLabel': { TW: 'OOC 保護（悄悄話時停用 Ctrl+Enter）', CN: 'OOC 保护（悄悄话时停用 Ctrl+Enter）', EN: 'OOC Protection (block Ctrl+Enter during whisper)', JP: 'OOC 保護（ささやき中は Ctrl+Enter を無効化）', KR: 'OOC 보호 (귓속말 중 Ctrl+Enter 차단)', DE: 'OOC-Schutz (Strg+Enter beim Flüstern blockieren)', FR: 'Protection OOC (bloquer Ctrl+Entrée en chuchotement)', RU: 'OOC-защита (блокировать Ctrl+Enter при шёпоте)', UA: 'OOC-захист (блокувати Ctrl+Enter при шепоті)' },
        'oocProtectNote': { TW: '悄悄話/BEEP 模式下，封鎖 Ctrl+Enter 以防止 OOC 內容作為普通對話發出', CN: '悄悄话/BEEP 模式下，封锁 Ctrl+Enter 以防止 OOC 内容作为普通对话发出', EN: 'In whisper/BEEP mode, blocks Ctrl+Enter to prevent OOC content from being sent as normal chat', JP: 'ささやき/BEEP モード中に Ctrl+Enter を封鎖し、OOC 内容が通常会話として送信されるのを防止', KR: '귓속말/BEEP 모드에서 Ctrl+Enter를 차단하여 OOC 내용이 일반 대화로 전송되는 것 방지', DE: 'Blockiert im Flüster-/BEEP-Modus Strg+Enter, damit OOC-Inhalt nicht als normaler Chat gesendet wird', FR: 'En mode chuchotement/BEEP, bloque Ctrl+Entrée pour éviter d\'envoyer du contenu OOC en chat normal', RU: 'В режиме шёпота/BEEP блокирует Ctrl+Enter, чтобы OOC не ушёл в обычный чат', UA: 'У режимі шепоту/BEEP блокує Ctrl+Enter, щоб OOC не пішов у звичайний чат' },
        'btnVisibilityLabel': { TW: '按鈕顯示設定', CN: '按钮显示设置', EN: 'Button Visibility', JP: 'ボタン表示設定', KR: '버튼 표시 설정', DE: 'Schaltflächen-Sichtbarkeit', FR: 'Visibilité des boutons', RU: 'Видимость кнопок', UA: 'Видимість кнопок' },
        'btnVisibilityNote': { TW: '控制 FCM 按鈕在各頁面的顯示狀態（至少須保留一個）', CN: '控制 FCM 按钮在各页面的显示状态（至少须保留一个）', EN: 'Control which screens show the FCM button (at least one must remain enabled)', JP: '各画面での FCM ボタン表示を制御（最低 1 つは有効に）', KR: '각 화면의 FCM 버튼 표시 제어 (최소 하나는 유지)', DE: 'Legt fest, auf welchen Bildschirmen die FCM-Schaltfläche erscheint (mindestens eine aktiv)', FR: 'Contrôle sur quels écrans le bouton FCM apparaît (au moins un actif)', RU: 'Где показывать кнопку FCM (хотя бы одна должна остаться включённой)', UA: 'Де показувати кнопку FCM (хоча б одна має лишитися увімкненою)' },
        'btnShowChatRoom': { TW: '聊天室按鈕', CN: '聊天室按钮', EN: 'ChatRoom button', JP: 'チャットルームのボタン', KR: '채팅방 버튼', DE: 'Raum-Schaltfläche', FR: 'Bouton salon', RU: 'Кнопка в комнате', UA: 'Кнопка в кімнаті' },
        'btnShowMainHall': { TW: '大廳按鈕', CN: '大厅按钮', EN: 'Main Hall button', JP: 'メインホールのボタン', KR: '메인 홀 버튼', DE: 'Haupthallen-Schaltfläche', FR: 'Bouton hall principal', RU: 'Кнопка в холле', UA: 'Кнопка в холі' },
        'btnShowProfile': { TW: '個人檔案按鈕', CN: '个人档案按钮', EN: 'Profile button', JP: 'プロフィールのボタン', KR: '프로필 버튼', DE: 'Profil-Schaltfläche', FR: 'Bouton profil', RU: 'Кнопка профиля', UA: 'Кнопка профілю' },

        // ── Profile 關係人快速搜尋（新功能）──────────────────────────
        'profileRelLabel': { TW: 'Profile 關係人快速搜尋', CN: 'Profile 关系人快速搜索', EN: 'Quick Search Profile Relations', JP: 'Profile 関係人クイック検索', KR: 'Profile 관계인 빠른 검색', DE: 'Schnellsuche für Profil-Beziehungen', FR: 'Recherche rapide des relations du profil', RU: 'Быстрый поиск связей профиля', UA: 'Швидкий пошук зв\'язків профілю' },
        'profileRelNote': { TW: '查看角色資料頁時，將主人／戀人等關係人的 ID 做成按鈕，點擊即開啟 FCM 人員查詢並帶入該 ID（須配合 Profile 保存功能）', CN: '查看角色资料页时，将主人／恋人等关系人的 ID 做成按钮，点击即打开 FCM 人员查询并带入该 ID（须配合 Profile 保存功能）', EN: 'On a character profile page, turn related people (owner/lovers) IDs into buttons — click to open FCM People search prefilled with that ID (requires the Profile save feature)', JP: 'キャラのプロフィール画面で、マスター／恋人など関係人の ID をボタン化。クリックで FCM の人物検索を開き ID を入力（Profile 保存機能が必要）', KR: '캐릭터 프로필 화면에서 주인／연인 등 관계인의 ID를 버튼으로 만들어 클릭 시 FCM 인물 검색을 열고 해당 ID를 입력 (Profile 저장 기능 필요)', DE: 'Wandelt auf einer Charakter-Profilseite die IDs verwandter Personen (Besitzer/Geliebte) in Schaltflächen um — Klick öffnet die FCM-Personensuche mit dieser ID (erfordert die Profil-Speicherfunktion)', FR: 'Sur une fiche de personnage, transforme les ID des relations (maître/amants) en boutons — cliquer ouvre la recherche FCM préremplie avec cet ID (nécessite la fonction d\'enregistrement de profil)', RU: 'На странице профиля превращает ID связанных людей (владелец/возлюбленные) в кнопки — клик открывает поиск людей FCM с этим ID (требуется функция сохранения профиля)', UA: 'На сторінці профілю перетворює ID пов\'язаних людей (власник/кохані) на кнопки — клік відкриває пошук людей FCM із цим ID (потрібна функція збереження профілю)' },
        'profileRelTitle': { TW: '🔍 關係人快速查詢', CN: '🔍 关系人快速查询', EN: '🔍 Quick Relation Lookup', JP: '🔍 関係人クイック検索', KR: '🔍 관계인 빠른 조회', DE: '🔍 Schnelle Beziehungssuche', FR: '🔍 Recherche rapide de relations', RU: '🔍 Быстрый поиск связей', UA: '🔍 Швидкий пошук зв\'язків' },
        'noBeepNotFriend': { TW: '非好友，無法私信', CN: '非好友，无法私信', EN: 'Not a friend — cannot BEEP', JP: 'フレンドではないため BEEP 不可', KR: '친구가 아니므로 BEEP 불가', DE: 'Kein Freund — BEEP nicht möglich', FR: 'Pas un ami — BEEP impossible', RU: 'Не друг — BEEP недоступен', UA: 'Не друг — BEEP недоступний' },
        'colorNone': { TW: '無色', CN: '无色', EN: 'No color', JP: '色なし', KR: '색상 없음', DE: 'Keine Farbe', FR: 'Sans couleur', RU: 'Без цвета', UA: 'Без кольору' },

        // ── 添加好友流程（新功能）──────────────────────────────────
        'addFriendTitle': { TW: '是否添加「{0}」為好友？', CN: '是否添加「{0}」为好友？', EN: 'Add "{0}" as a friend?', JP: '「{0}」をフレンドに追加しますか？', KR: '"{0}" 님을 친구로 추가할까요?', DE: '„{0}" als Freund hinzufügen?', FR: 'Ajouter « {0} » comme ami ?', RU: 'Добавить «{0}» в друзья?', UA: 'Додати «{0}» у друзі?' },
        'addFriendNotifyHint': { TW: '（可發送通知給對方，需有 FCM）', CN: '（可发送通知给对方，需有 FCM）', EN: '(Can notify them — requires FCM)', JP: '（相手に通知を送れます。FCM が必要）', KR: '(상대에게 알림 전송 가능 — FCM 필요)', DE: '(Kann benachrichtigt werden — FCM erforderlich)', FR: '(Peut être notifié — FCM requis)', RU: '(Можно уведомить — требуется FCM)', UA: '(Можна сповістити — потрібен FCM)' },
        'btnAgree': { TW: '同意', CN: '同意', EN: 'Agree', JP: '同意', KR: '동의', DE: 'Zustimmen', FR: 'Accepter', RU: 'Согласен', UA: 'Погодитись' },
        'btnAgreeNotify': { TW: '同意且通知', CN: '同意并通知', EN: 'Agree & Notify', JP: '同意して通知', KR: '동의 및 알림', DE: 'Zustimmen & benachrichtigen', FR: 'Accepter et notifier', RU: 'Согласиться и уведомить', UA: 'Погодитись і сповістити' },
        'btnViewProfile': { TW: '查看', CN: '查看', EN: 'View', JP: '表示', KR: '보기', DE: 'Ansehen', FR: 'Voir', RU: 'Профиль', UA: 'Профіль' },
        'friendReqNeedRoom': { TW: '需與對方在同一房間才能發送通知', CN: '需与对方在同一房间才能发送通知', EN: 'Must be in the same room to notify', JP: '通知するには相手と同じ部屋にいる必要があります', KR: '알림하려면 상대와 같은 방에 있어야 합니다', DE: 'Zum Benachrichtigen müsst ihr im selben Raum sein', FR: 'Vous devez être dans le même salon pour notifier', RU: 'Чтобы уведомить, нужно быть в одной комнате', UA: 'Щоб сповістити, треба бути в одній кімнаті' },
        'friendReqIncoming': { TW: '{0} 發送好友邀請，請問你是否同意？', CN: '{0} 发送好友邀请，请问你是否同意？', EN: '{0} sent you a friend request. Do you accept?', JP: '{0} からフレンド申請が届きました。承認しますか？', KR: '{0} 님이 친구 요청을 보냈습니다. 수락하시겠어요?', DE: '{0} hat dir eine Freundschaftsanfrage gesendet. Annehmen?', FR: '{0} vous a envoyé une demande d\'ami. Accepter ?', RU: '{0} отправил(а) запрос в друзья. Принять?', UA: '{0} надіслав(ла) запит у друзі. Прийняти?' },
        'friendReqSent': { TW: '📩 已發送好友邀請通知給「{0}」', CN: '📩 已发送好友邀请通知给「{0}」', EN: '📩 Friend request notification sent to "{0}"', JP: '📩 「{0}」にフレンド申請の通知を送信しました', KR: '📩 "{0}" 님에게 친구 요청 알림을 보냈습니다', DE: '📩 Freundschaftsanfrage an „{0}" gesendet', FR: '📩 Notification de demande d\'ami envoyée à « {0} »', RU: '📩 Уведомление о запросе в друзья отправлено «{0}»', UA: '📩 Сповіщення про запит у друзі надіслано «{0}»' },
        'friendReqAdded': { TW: '✓ 已將「{0}」加為好友', CN: '✓ 已将「{0}」加为好友', EN: '✓ Added "{0}" as a friend', JP: '✓ 「{0}」をフレンドに追加しました', KR: '✓ "{0}" 님을 친구로 추가했습니다', DE: '✓ „{0}" als Freund hinzugefügt', FR: '✓ « {0} » ajouté comme ami', RU: '✓ «{0}» добавлен(а) в друзья', UA: '✓ «{0}» додано у друзі' },

        // ── 房間類型 / 分享（新功能）───────────────────────────────
        'roomTypeMap': { TW: '地圖', CN: '地图', EN: 'Map', JP: 'マップ', KR: '맵', DE: 'Karte', FR: 'Carte', RU: 'Карта', UA: 'Карта' },
        'roomTypeMix': { TW: '混合', CN: '混合', EN: 'Hybrid', JP: 'ハイブリッド', KR: '혼합', DE: 'Hybrid', FR: 'Hybride', RU: 'Гибрид', UA: 'Гібрид' },
        'roomLockedCanJoin': { TW: '已上鎖，你有進入權限', CN: '已上锁，你有进入权限', EN: 'Locked — you can join', JP: 'ロック中 — 参加可能', KR: '잠김 — 참가 가능', DE: 'Gesperrt — du kannst beitreten', FR: 'Verrouillé — vous pouvez entrer', RU: 'Заблокировано — вы можете войти', UA: 'Заблоковано — ви можете увійти' },
        'roomLockedNoAccess': { TW: '已上鎖，你沒有進入權限', CN: '已上锁，你没有进入权限', EN: 'Locked — no access', JP: 'ロック中 — 参加不可', KR: '잠김 — 접근 불가', DE: 'Gesperrt — kein Zugang', FR: 'Verrouillé — pas d\'accès', RU: 'Заблокировано — нет доступа', UA: 'Заблоковано — немає доступу' },
        'roomHereBadge': { TW: '🏠 你', CN: '🏠 你', EN: '🏠 You', JP: '🏠 あなた', KR: '🏠 나', DE: '🏠 Du', FR: '🏠 Vous', RU: '🏠 Вы', UA: '🏠 Ви' },
        'roomReenter': { TW: '重新進入', CN: '重新进入', EN: 'Re-enter', JP: '再入室', KR: '다시 입장', DE: 'Erneut betreten', FR: 'Revenir', RU: 'Войти снова', UA: 'Увійти знову' },
        'roomReenterConfirm': { TW: '你已經在「{0}」中了。\n確定要重新進入嗎？', CN: '你已经在「{0}」中了。\n确定要重新进入吗？', EN: 'You are already in "{0}".\nRe-enter the room?', JP: 'すでに「{0}」にいます。\n再入室しますか？', KR: '이미 "{0}" 방에 있습니다.\n다시 입장할까요?', DE: 'Du bist bereits in „{0}".\nErneut betreten?', FR: 'Vous êtes déjà dans « {0} ».\nY revenir ?', RU: 'Вы уже в комнате «{0}».\nВойти снова?', UA: 'Ви вже в кімнаті «{0}».\nУвійти знову?' },
        'btnCancel': { TW: '取消', CN: '取消', EN: 'Cancel', JP: 'キャンセル', KR: '취소', DE: 'Abbrechen', FR: 'Annuler', RU: 'Отмена', UA: 'Скасувати' },
        'btnConfirm': { TW: '確認', CN: '确认', EN: 'Confirm', JP: '確認', KR: '확인', DE: 'Bestätigen', FR: 'Confirmer', RU: 'Подтвердить', UA: 'Підтвердити' },
        'roomGo': { TW: '🚪 前往', CN: '🚪 前往', EN: '🚪 Go', JP: '🚪 移動', KR: '🚪 이동', DE: '🚪 Los', FR: '🚪 Aller', RU: '🚪 Перейти', UA: '🚪 Перейти' },
        'beepSummonConfirm': { TW: '請確定您有召喚對方的權限，否則對方只會收到文字 "summon"。\n\n確定要召喚「{0}」嗎？', CN: '请确定您有召唤对方的权限，否则对方只会收到文字 "summon"。\n\n确定要召唤「{0}」吗？', EN: 'Make sure you have permission to summon them, otherwise they will only receive the text "summon".\n\nSummon "{0}"?', JP: '召喚する権限があることを確認してください。なければ相手には "summon" というテキストのみ届きます。\n\n「{0}」を召喚しますか？', KR: '상대를 소환할 권한이 있는지 확인하세요. 없으면 상대는 "summon" 텍스트만 받습니다.\n\n"{0}" 님을 소환할까요?', DE: 'Stelle sicher, dass du die Berechtigung zum Herbeirufen hast, sonst erhält die Person nur den Text „summon".\n\n„{0}" herbeirufen?', FR: 'Assurez-vous d\'avoir la permission de convoquer, sinon la personne ne recevra que le texte « summon ».\n\nConvoquer « {0} » ?', RU: 'Убедитесь, что у вас есть право призывать, иначе собеседник получит только текст «summon».\n\nПризвать «{0}»?', UA: 'Переконайтеся, що маєте право прикликати, інакше співрозмовник отримає лише текст «summon».\n\nПрикликати «{0}»?' },

        // ── 通用 UI（統一走 i18n，取代 inline 特例）──────────────────
        'btnRemove': { TW: '移除', CN: '移除', EN: 'Remove', JP: '削除', KR: '삭제', DE: 'Entfernen', FR: 'Retirer', RU: 'Удалить', UA: 'Видалити' },
        'btnAddConfirm': { TW: '加入', CN: '加入', EN: 'Add', JP: '追加', KR: '추가', DE: 'Hinzufügen', FR: 'Ajouter', RU: 'Добавить', UA: 'Додати' },
        'btnRefresh': { TW: '重新整理', CN: '刷新', EN: 'Refresh', JP: '更新', KR: '새로고침', DE: 'Aktualisieren', FR: 'Actualiser', RU: 'Обновить', UA: 'Оновити' },
        'btnAddGhost': { TW: '＋幽靈', CN: '＋幽灵', EN: '＋Ghost', JP: '＋ゴースト', KR: '＋고스트', DE: '＋Geist', FR: '＋Fantôme', RU: '＋Призрак', UA: '＋Привид' },
        'btnRmGhost': { TW: '－幽靈', CN: '－幽灵', EN: '－Ghost', JP: '－ゴースト', KR: '－고스트', DE: '－Geist', FR: '－Fantôme', RU: '－Призрак', UA: '－Привид' },
        'btnClear': { TW: '清除', CN: '清除', EN: 'Clear', JP: 'クリア', KR: '지우기', DE: 'Löschen', FR: 'Effacer', RU: 'Очистить', UA: 'Очистити' },
        'btnClearing': { TW: '清除中...', CN: '清除中...', EN: 'Clearing...', JP: 'クリア中...', KR: '지우는 중...', DE: 'Wird gelöscht...', FR: 'Effacement...', RU: 'Очистка...', UA: 'Очищення...' },
        'btnSearch': { TW: '搜尋', CN: '搜索', EN: 'Search', JP: '検索', KR: '검색', DE: 'Suchen', FR: 'Chercher', RU: 'Поиск', UA: 'Пошук' },
        'confirmRmWhite': { TW: '移除「{0}」白名單？', CN: '移除「{0}」白名单？', EN: 'Remove "{0}" from whitelist?', JP: '「{0}」をホワイトリストから削除しますか？', KR: '"{0}" 님을 화이트리스트에서 삭제할까요?', DE: '„{0}" von der Whitelist entfernen?', FR: 'Retirer « {0} » de la liste blanche ?', RU: 'Убрать «{0}» из белого списка?', UA: 'Прибрати «{0}» з білого списку?' },
        'confirmAddWhite': { TW: '將「{0}」加入白名單？', CN: '将「{0}」加入白名单？', EN: 'Add "{0}" to whitelist?', JP: '「{0}」をホワイトリストに追加しますか？', KR: '"{0}" 님을 화이트리스트에 추가할까요?', DE: '„{0}" zur Whitelist hinzufügen?', FR: 'Ajouter « {0} » à la liste blanche ?', RU: 'Добавить «{0}» в белый список?', UA: 'Додати «{0}» до білого списку?' },
        'confirmRmBlack': { TW: '移除「{0}」黑名單？', CN: '移除「{0}」黑名单？', EN: 'Remove "{0}" from blacklist?', JP: '「{0}」をブラックリストから削除しますか？', KR: '"{0}" 님을 블랙리스트에서 삭제할까요?', DE: '„{0}" von der Blacklist entfernen?', FR: 'Retirer « {0} » de la liste noire ?', RU: 'Убрать «{0}» из чёрного списка?', UA: 'Прибрати «{0}» з чорного списку?' },
        'confirmRmGhost': { TW: '移除「{0}」幽靈？', CN: '移除「{0}」幽灵？', EN: 'Remove "{0}" from ghost?', JP: '「{0}」をゴーストから削除しますか？', KR: '"{0}" 님을 고스트에서 삭제할까요?', DE: '„{0}" von der Geisterliste entfernen?', FR: 'Retirer « {0} » de la liste fantôme ?', RU: 'Убрать «{0}» из списка призраков?', UA: 'Прибрати «{0}» зі списку привидів?' },
        'avReloadTitle': { TW: '點擊重新抓取頭像', CN: '点击重新抓取头像', EN: 'Click to reload avatar', JP: 'クリックでアバター再取得', KR: '클릭하여 아바타 다시 불러오기', DE: 'Zum Neuladen des Avatars klicken', FR: 'Cliquer pour recharger l\'avatar', RU: 'Нажмите, чтобы обновить аватар', UA: 'Натисніть, щоб оновити аватар' },
        'togNickToBCName': { TW: '切換為BC名稱', CN: '切换为BC名称', EN: 'Switch to BC name', JP: 'BC名に切替', KR: 'BC 이름으로 전환', DE: 'Zum BC-Namen wechseln', FR: 'Passer au nom BC', RU: 'Переключить на имя BC', UA: 'Перемкнути на назву BC' },
        'togNickToNick': { TW: '切換為暱稱', CN: '切换为昵称', EN: 'Switch to nickname', JP: 'ニックネームに切替', KR: '닉네임으로 전환', DE: 'Zum Spitznamen wechseln', FR: 'Passer au surnom', RU: 'Переключить на ник', UA: 'Перемкнути на нік' },
        'btnSnapshotTitle': { TW: '快照目前名單（強制重建頭像）', CN: '快照当前名单（强制重建头像）', EN: 'Snapshot current list (force rebuild)', JP: '現在のリストをスナップショット（強制再構築）', KR: '현재 목록 스냅샷 (강제 재생성)', DE: 'Aktuelle Liste erfassen (Neuaufbau erzwingen)', FR: 'Capturer la liste actuelle (reconstruction forcée)', RU: 'Снимок текущего списка (принуд. пересборка)', UA: 'Знімок поточного списку (примус. перебудова)' },
        'roomPrivPrefix': { TW: '[私人] ', CN: '[私人] ', EN: '[Private] ', JP: '[プライベート] ', KR: '[비공개] ', DE: '[Privat] ', FR: '[Privé] ', RU: '[Приватная] ', UA: '[Приватна] ' },
        'roomFull': { TW: '⚠ 房間已滿', CN: '⚠ 房间已满', EN: '⚠ Full', JP: '⚠ 満室', KR: '⚠ 가득 참', DE: '⚠ Voll', FR: '⚠ Plein', RU: '⚠ Заполнено', UA: '⚠ Заповнено' },
        'roomGoPrompt': { TW: '前往此房間？', CN: '前往此房间？', EN: 'Go to room?', JP: 'この部屋へ移動しますか？', KR: '이 방으로 이동할까요?', DE: 'Zum Raum gehen?', FR: 'Aller au salon ?', RU: 'Перейти в комнату?', UA: 'Перейти в кімнату?' },
        'roomPrivShort': { TW: '(私人)', CN: '(私人)', EN: '(Priv)', JP: '(非公開)', KR: '(비공개)', DE: '(Privat)', FR: '(Privé)', RU: '(Прив)', UA: '(Прив)' },
        'roomPrivateHidden': { TW: '(私密)', CN: '(私密)', EN: '(Private)', JP: '(プライベート)', KR: '(비공개)', DE: '(Privat)', FR: '(Privé)', RU: '(Приватная)', UA: '(Приватна)' },
        'peopleDbNotConnected': { TW: '資料庫未連線，請確認儲存模式已設定', CN: '数据库未连接，请确认存储模式已设定', EN: 'DB not connected — set a save mode in Settings', JP: 'DB未接続 — 設定で保存モードを設定してください', KR: 'DB 미연결 — 설정에서 저장 모드를 지정하세요', DE: 'DB nicht verbunden — Speichermodus in den Einstellungen wählen', FR: 'BD non connectée — définissez un mode de sauvegarde', RU: 'БД не подключена — задайте режим сохранения', UA: 'БД не під\'єднана — задайте режим збереження' },
        'shareNeedRoom': { TW: '需在聊天室中才能分享', CN: '需在聊天室中才能分享', EN: 'Must be in a chat room to share', JP: '共有はルーム内でのみ可能', KR: '채팅방 안에서만 공유 가능', DE: 'Zum Teilen im Raum sein', FR: 'Doit être dans un salon pour partager', RU: 'Делиться можно только в комнате', UA: 'Ділитися можна лише в кімнаті' },
        'pageInfo': { TW: '第 {0} / {1} 頁', CN: '第 {0} / {1} 页', EN: 'Page {0} / {1}', JP: '{0} / {1} ページ', KR: '{0} / {1} 페이지', DE: 'Seite {0} / {1}', FR: 'Page {0} / {1}', RU: 'Стр. {0} / {1}', UA: 'Стор. {0} / {1}' },
        'sortFavFirst': { TW: '最愛優先', CN: '最爱优先', EN: 'Fav First', JP: 'お気に入り優先', KR: '즐겨찾기 우선', DE: 'Favoriten zuerst', FR: 'Favoris d\'abord', RU: 'Избранное сначала', UA: 'Обране спершу' },
        'sortFriendFirst': { TW: '好友優先', CN: '好友优先', EN: 'Friends First', JP: 'フレンド優先', KR: '친구 우선', DE: 'Freunde zuerst', FR: 'Amis d\'abord', RU: 'Друзья сначала', UA: 'Друзі спершу' },
        'sortNameOnly': { TW: '名稱優先', CN: '名称优先', EN: 'Name', JP: '名前', KR: '이름', DE: 'Name', FR: 'Nom', RU: 'Имя', UA: 'Ім\'я' },
        'setSecUI': { TW: '⚙ UI 管理', CN: '⚙ UI 管理', EN: '⚙ UI Management', JP: '⚙ UI 管理', KR: '⚙ UI 관리', DE: '⚙ UI-Verwaltung', FR: '⚙ Gestion UI', RU: '⚙ Управление UI', UA: '⚙ Керування UI' },
        'setSecChat': { TW: '⚙ 聊天室管理', CN: '⚙ 聊天室管理', EN: '⚙ Chat Room', JP: '⚙ チャットルーム', KR: '⚙ 채팅방', DE: '⚙ Chatraum', FR: '⚙ Salon', RU: '⚙ Комната', UA: '⚙ Кімната' },
        'avCacheCleared': { TW: '✓ 頭像快取已清除', CN: '✓ 头像缓存已清除', EN: '✓ Cache cleared', JP: '✓ アバターキャッシュを消去', KR: '✓ 캐시 삭제됨', DE: '✓ Cache geleert', FR: '✓ Cache vidé', RU: '✓ Кэш очищен', UA: '✓ Кеш очищено' },
        'noFriendsToLoad': { TW: '沒有需要載入的好友', CN: '没有需要加载的好友', EN: 'No friends need loading', JP: '読み込むフレンドがいません', KR: '불러올 친구가 없습니다', DE: 'Keine Freunde zu laden', FR: 'Aucun ami à charger', RU: 'Нет друзей для загрузки', UA: 'Немає друзів для завантаження' },
        'avWaitLeft': { TW: '等待 BC 緩存外觀... 剩餘 {0} 秒', CN: '等待 BC 缓存外观... 剩余 {0} 秒', EN: 'Waiting for BC... {0}s left', JP: 'BCの外見キャッシュ待機... 残り {0} 秒', KR: 'BC 외형 캐시 대기... {0}초 남음', DE: 'Warte auf BC... noch {0}s', FR: 'Attente de BC... {0}s restantes', RU: 'Ожидание BC... осталось {0}с', UA: 'Очікування BC... лишилось {0}с' },
        'avWait': { TW: '等待 BC 緩存外觀... {0} 秒', CN: '等待 BC 缓存外观... {0} 秒', EN: 'Waiting for BC... {0}s', JP: 'BCの外見キャッシュ待機... {0} 秒', KR: 'BC 외형 캐시 대기... {0}초', DE: 'Warte auf BC... {0}s', FR: 'Attente de BC... {0}s', RU: 'Ожидание BC... {0}с', UA: 'Очікування BC... {0}с' },
        'avSnapshotting': { TW: '開始截圖...', CN: '开始截图...', EN: 'Snapshotting...', JP: 'スナップショット中...', KR: '스냅샷 중...', DE: 'Erfasse...', FR: 'Capture...', RU: 'Снимок...', UA: 'Знімок...' },
        'wceTagDetected': { TW: '偵測到 WCE Profiles', CN: '检测到 WCE Profiles', EN: 'WCE detected', JP: 'WCE Profiles を検出', KR: 'WCE Profiles 감지됨', DE: 'WCE erkannt', FR: 'WCE détecté', RU: 'Обнаружен WCE', UA: 'Виявлено WCE' },
        'colorEditLabel': { TW: '修改顏色', CN: '修改颜色', EN: 'Color', JP: '色を変更', KR: '색상 변경', DE: 'Farbe', FR: 'Couleur', RU: 'Цвет', UA: 'Колір' },
        'cmdProfilesDesc': { TW: '<篩選> - 開啟人員查詢（依名稱或 ID 篩選）', CN: '<筛选> - 打开人员查询（按名称或 ID 筛选）', EN: '<filter> - Open People search (filter by name or ID)', JP: '<フィルタ> - 人物検索を開く（名前かIDで絞り込み）', KR: '<필터> - 인물 검색 열기 (이름 또는 ID로 필터)', DE: '<Filter> - Personensuche öffnen (nach Name oder ID)', FR: '<filtre> - Ouvrir la recherche de personnes (par nom ou ID)', RU: '<фильтр> - Открыть поиск людей (по имени или ID)', UA: '<фільтр> - Відкрити пошук людей (за іменем або ID)' },
        'roomShareBtn': { TW: '分享', CN: '分享', EN: 'Share', JP: '共有', KR: '공유', DE: 'Teilen', FR: 'Partager', RU: 'Поделиться', UA: 'Поділитися' },
        'roomJoinRoomBtn': { TW: '加入房間', CN: '加入房间', EN: 'Join Room', JP: 'ルームに参加', KR: '방 참가', DE: 'Raum betreten', FR: 'Rejoindre le salon', RU: 'Войти в комнату', UA: 'Увійти в кімнату' },
        'roomShareNeedRoom': { TW: '需在聊天室中才能分享房間', CN: '需在聊天室中才能分享房间', EN: 'Must be in a chat room to share', JP: 'ルーム内でのみ共有できます', KR: '채팅방 안에서만 공유할 수 있습니다', DE: 'Zum Teilen im Raum sein', FR: 'Doit être dans un salon pour partager', RU: 'Делиться можно только в комнате', UA: 'Ділитися можна лише в кімнаті' },
        'roomShareIntro': { TW: '{0} 分享了一個房間信息', CN: '{0} 分享了一个房间信息', EN: '{0} shared a room', JP: '{0} がルーム情報を共有しました', KR: '{0} 님이 방 정보를 공유했습니다', DE: '{0} hat einen Raum geteilt', FR: '{0} a partagé un salon', RU: '{0} поделился(ась) комнатой', UA: '{0} поділився(лась) кімнатою' },
        'roomShareLocalDone': { TW: '📤 已分享房間「{0}」到聊天室', CN: '📤 已分享房间「{0}」到聊天室', EN: '📤 Shared room "{0}" to the chat', JP: '📤 ルーム「{0}」をチャットに共有しました', KR: '📤 방 "{0}" 을(를) 채팅에 공유했습니다', DE: '📤 Raum „{0}" im Chat geteilt', FR: '📤 Salon « {0} » partagé dans le chat', RU: '📤 Комната «{0}» отправлена в чат', UA: '📤 Кімнату «{0}» надіслано в чат' },
    };

    window.Liko.__Sys_i18n__.register('FCM', FCM_STRINGS);
})();
